### ISSUE TITLE
Obra social

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1007]
### Comportamiento actual
No muestra obra social en punto de inicio y en detalle del turno antes de confirmar - Si se muestra en arancelamiento. 

(demo y producción)
### Resultado esperado 
Ver obra social en punto de inicio y al momento de dar el turno. 
### Pasos para reproducir el problema 
1. buscar un paciente con obra social en punto de inicio
2. dar un turno
3.

**Comment by kroce** [comment]
@Silvinagabriela este issue sigue activo?
