### ISSUE TITLE
RUP: Receta de un medicamento

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1014]
### Comportamiento actual
* Al iniciar prestación a un paciente y cargo el concepto Snomed "Receta de un Medicamento" cuando guardo la prestación, se me abre mensaje de error. 

### Resultado esperado 
* Que el concepto "Receta de un medicamento" me permita guardar y validar la prestación.

### Pasos para reproducir el problema 
1. Iniciar prestación a paciente 
2. Agregar concepto Snomed "Receta de un Medicamento"
3. Visualizar mensaje de error

**Comment by liquid36** [comment]
Había un problema en la base de datos. Ya quedo corregido.
