### ISSUE TITLE
MPI - Relaciones Familiares pacientes s/DNI

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1017]
### Comportamiento actual
El sistema solicita como dato obligatorio el DNI de la relación, entonces ante este ejemplo no es posible realizar la vinculación
Ej: no permite relacionar un bebé sin DNI a una madre.

### Resultado esperado 
* ¿Que espera que suceda?
Poder vincular un temporal o un validado a un temporal sin DNI. 
### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by milagrosn** [comment]
resuelto!!
