### ISSUE TITLE
CITAS - Obra Social en el Punto de Inicio

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1030]
### Comportamiento actual
Muestra la obra social luego de otorgar un turno

### Resultado esperado 
Mostrar la Obra social luego de validar el paciente
### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by NicoDino** [comment]
:heavy_check_mark: Punto de inicio muestra la obra social en la información del paciente según padrones
