### ISSUE TITLE
TOP - Anular solicitudes

### ISSUE THREAD

**Issue by palita1991** [andes/app#1033]
### Comportamiento actual
* Usuario del módulo TOP sólo puede desactivar solicitudes pendientes para quitarlas de la bandeja de entrada si selecciona todos los permisos del módulo (Anular Solicitudes y Edición de Reglas). 

### Resultado esperado 
* Usuario del módulo TOP debería poder desactivar solicitudes pendientes para quitarlas de la bandeja de entrada solo seleccionando el permiso especial de "Anular Solicitudes" o teniendo todos los permisos de dicho módulo. 

### Pasos para reproducir el problema 
1. Módulo Solicitudes - Listado de solicitudes pendientes.
2. En la columna de "Operaciones" se encuentra un botón para anular las solicitudes pendientes que no correspondan.
3. Este botón sólo aparece cuando el usuario del módulo TOP posee todos los permisos (Anular Solicitudes y Edición de Reglas).

**Comment by NicoDino** [comment]
La arquitectura de carpetas y el path del routing para no respeta la [Guía de desarrollo](https://github.com/andes/andes/wiki/C%C3%B3digo-fuente#routing)
