### ISSUE TITLE
MPI- visualización del paciente en header

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#1036]
### Comportamiento actual
* Cuando agrego un paciente, visualizo su HUDS y nuevamente ingreso a MPI para agregar otro paciente, sigo visualizando el detalle de ese paciente

### Pasos para reproducir el problema 
1. Ingreso al modulo de RUP
2. VIsualizo la HUDS del paciente.
3. Sin tocar el boton de volver, ingreso desde el menú hamburguesa al modulo MPI.
4. Veo en el header los datos del paciente al cual le visualice la HUDS en el punto 2.

--

![image](https://user-images.githubusercontent.com/30051357/50782635-6079f100-1287-11e9-9170-91d310e2076c.png)

**Comment by negro89** [comment]
Parece que es un tema de plex. Lo va a ver naty.
