### ISSUE TITLE
CITAS - Pacientes fuera de agenda

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1052]
### Comportamiento actual
(Producción) En auditoria de pacientes fuera de agenda se visualizan los pacientes de todos los efectores. 

### Resultado esperado 
Mostrar solo los pacientes fuera de agenda del efector en el que estoy logueado
### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by condorpiedra** [comment]
se resuelve en versión v4.3.4
