### ISSUE TITLE
RUP - Procedimientos y solicitudes

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1060]
### Comportamiento actual
actualmente se muestran las solicitudes cargadas como procedimientos

### Resultado esperado 
Visualizarlos correctamente a ambos 

### Pasos para reproducir el problema 
1. Iniciar una prestación
2. cargar una solicitud
3. guardar y validar
4. visualizar huds/iniciar nuevamente una prestación en ese paciente. 
5. La solicitud cargada se ve como un procedimiento.

**Comment by NicoDino** [comment]
Fixed
