### ISSUE TITLE
RUP - Visualización de un adjunto

### ISSUE THREAD

**Issue by jfgabriel** [andes/app#1064]
### Comportamiento actual
* Cuando se muestra un registro en la HUDS, hay dos errores:
1. El título del elemento está duplicado (ver en la imagen "Adjuntar archivo de...."
2. En la evolución se muestra el HTML.

![image](https://user-images.githubusercontent.com/16528734/51852504-fcd26900-2304-11e9-8614-ff805527c0ef.png)

**Comment by andrrrl** [comment]
Podemos agregar que el layout es un espanto...
Agrego esta tarea dentro del rediseño de la HUDS que se está llevando a cabo.

**Comment by palita1991** [comment]
Resuelto.
