### ISSUE TITLE
RUP - Filtro DNI de paciente - Pacientes fuera de agenda

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1070]
### Comportamiento actual
Al filtrar por DNI de paciente no muestra resultados en paciente fuera de agenda 
### Resultado esperado 
Que al filtrar por DNI realice la búsqueda tanto en agenda como en paciente fuera de agenda. 
### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by milagrosn** [comment]
Resuelto!
