### ISSUE TITLE
RUP - Consulta de Odontología (vinculaciones)

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1071]
### Comportamiento actual
Cuando se selecciona más de una cara de un mismo diente y se selecciona un concepto, el nuevo concepto figura relacionado con todas las caras seleccionadas:
![image](https://user-images.githubusercontent.com/25707055/57233193-8a081680-6ff4-11e9-8ae8-71191c1484fe.png)
Pero en la imagen del odontograma figura solo pintada con el color del concepto ingresado solo una de las caras seleccionadas. ![image](https://user-images.githubusercontent.com/25707055/57233090-5d53ff00-6ff4-11e9-96b0-52203877e768.png)
Luego, al desvincular solo una de las caras, desde el botón de desvinculación del item de *Relacionado con* del elemento del concepto seleccionado, desaparecen todos los items de *Relacionado con*.  (Solo sucede cuando se seleccionan caras de un mismo diente)
### Resultado esperado 
Todas las caras vinculadas al concepto seccionada deber aparecer pintadas con el color del concepto.
Se debe desvincular solo la cara seleccionada.

### Pasos para reproducir el problema 
1. Agregar el odontograma a la consulta.
2. Tildar checkbox 'Seleccionar piezas/caras múltiples' . ![image](https://user-images.githubusercontent.com/25707055/57233968-1404af00-6ff6-11e9-9dae-7ff2568aec0b.png)
3. Seleccionar múltiples piezas.
3. Seleccionar varias caras de un mismo diente
4. Agregar un concepto Ej. Arreglo
5. Una vez agregado el concepto desvincular una de las caras vinculadas.

**Comment by lucasgonzalezm** [comment]
La desvinculación de una sola cara (la seleccionada) no se hizo porque no fue el requerimiento. Podría ponerse esto como una nueva US.
El bug queda entonces en que no queda pintado las caras seleccionadas

**Comment by lucasgonzalezm** [comment]
Fijarse también que cuando se desvincula, el cartel de confirmación pone otro nombre (la cara anterior del seleccionado). Fijarse si lo guarda bien en la base de datos también

**Comment by andrrrl** [comment]
@lucasgonzalezm no pude reproducir el problema, desde la ramas master de app y api, conexión a base demo.
Recuerdo que me mostraste el problema, pero me funciona bien, podés reconfirmar :thinking:

**Comment by lucasgonzalezm** [comment]
@andrrrl perdón la demora. Sigue ocurriendo en demo

[![image](https://user-images.githubusercontent.com/18200503/58878065-c9378f00-86a8-11e9-8fe4-ae9b3069664e.png)](https://www.loom.com/share/7fe72a40acda44eb8ef4e96b23825998)

**Comment by andrrrl** [comment]
Hay un PR que mejora y soluciona ese bug en https://github.com/andes/app/pull/1304

**Comment by plammel** [comment]
La imagen de selección de caras se rompe:
![image](https://user-images.githubusercontent.com/25707055/64122709-c10af080-cd78-11e9-9fcf-3f70141d079e.png)
1. Seleccionar múltiples caras de múltiples dientes.
2. Agregar un concepto nuevo, por ejemplo, un arreglo.
3. Desvincular las caras de los dientes desde los boxes de "Relacionado con" del panel del nuevo concepto asignado.
4. Asignar un concepto más.

**Comment by plammel** [comment]
Al presionar el botón "Limpiar selección", dicho botón desaparece, pero la selección y los vínculos con el procedimiento ingresado permanecen.

![image](https://user-images.githubusercontent.com/25707055/64126307-a722db00-cd83-11e9-93e2-11153f2be389.png)

**Comment by andrrrl** [comment]
Se cierra,se soluciona en PR #1304
