### ISSUE TITLE
Citas: Espacios fisicos

### ISSUE THREAD

**Issue by maryojeda** [andes/app#1075]
### Comportamiento actual
* Cuando se intenta filtrar por edificios el mapa muestra todos los consultorios, de todos los edificios pertenecientes al mismo efector.

### Resultado esperado 
* Se debería poder filtrar por edificios. Principalmente en los efectores mas grandes.

### Pasos para reproducir el problema 
1. Ir a citas: espacios fisicos.
2. Seleccionar un edificio.
3. Seleccionar el boton buscar.

Aparecen todos los consultorios juntos.

**Comment by Silvinagabriela** [comment]
@maryojeda en que servidor?

**Comment by palita1991** [comment]
Se resuelve en v4.4.11.
