### ISSUE TITLE
CITAS - Agendas Dinámicas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1085]
### Comportamiento actual
En el panel de turnos las agendas dinámicas no muestran la hora de la agenda

### Resultado esperado 
Mostrar la hora en agendas dinámicas 
### Pasos para reproducir el problema 
1. 
2. 
3. 

![image](https://user-images.githubusercontent.com/38788179/52565831-b7bf3400-2de6-11e9-9189-271797e4a0b1.png)

**Comment by milagrosn** [comment]
Listo!
