### ISSUE TITLE
CITAS - Gestor de agendas- calendario fecha

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1087]
### Comportamiento actual
En el gestor de agendas, al seleccionar una fecha futura para poder filtrar las agendas, es necesario marcar primero fecha *hasta* para luego poder seleccionar en el calendario fecha *desde*
### Resultado esperado 
Mostrar activas todas las fechas en el calendario 

### Pasos para reproducir el problema 
1. ingresar al gestor
2. intentar marcar una fecha a futuro en el calendario "fecha desde"
3. 

![image](https://user-images.githubusercontent.com/38788179/52584715-90ca2780-2e11-11e9-8bf8-d7350ad292c8.png)

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
