### ISSUE TITLE
Filtro de solicitudes

### ISSUE THREAD

**Issue by sychus** [andes/app#1095]
### Comportamiento actual
* Cuando realizo el filtrado de las solicitudes por estado AUDITORIA, muestra las que tienen turno dado además de las que requieren auditoria.

### Resultado esperado 
*Sólo me debe mostrar por auditoria.

**Comment by lucasgonzalezm** [comment]
Probar en la base de datos de testing de la subse, parado en Castro, 19/09/2018 en entrada
![Selection_002](https://user-images.githubusercontent.com/18200503/57229060-9a67c380-6feb-11e9-9f48-86e0adddd5d9.png)



Algo raro, posiblemente problemas con la BD de la subse. Una solicitud con dos estados
![image](https://user-images.githubusercontent.com/18200503/57229354-3eea0580-6fec-11e9-9798-adab4e6e9551.png)

También me pasó, tratando de replicar el issue, que había una solicitud que no mostraba el estado. Era de turno dado porque cuando filtraba por estado, era el único estado donde aparecía. No lo puedo replicar pero hay algo raro ahí

**Comment by plammel** [comment]
El issue se debe a registros que no quedaron bien generados en versiones anteriores. La query de consulta de solicitudes como tal está correcta. El error no pudo reproducirse con datos generados en las últimas versiones. El issue queda cerrado.

**Comment by lucasgonzalezm** [comment]
Se reabre porque se registró en producción un caso reciente (29/05/2019)
