### ISSUE TITLE
CITAS - Auditar Prestación

### ISSUE THREAD

**Issue by palita1991** [andes/app#1110]
### Comportamiento actual
* Al iniciar prestación de un paciente fuera de agenda, cargo diagnostico, guardo y valido la prestación, rompo la validación y cargo un nuevo diagnostico, me dirijo a auditar dicha prestación y se visualizan dos registros de prestación para ese paciente. 

### Resultado esperado 
* Visualizar correctamente los registros de la prestación. 

### Pasos para reproducir el problema 
1. Iniciar Registro de Prestación a un paciente fuera de agenda seleccionando fecha, hora y tipo de prestación y un paciente.
2. Se le carga un diagnostico al paciente, se guarda y se valida la prestación.
3. Romper la validación de la prestación y agregar un diagnostico nuevo. 
4. Ir a auditar la prestación y visualizar que aparecen dos registros de prestación para el paciente, uno con el primer diagnostico y otro con el diagnostico que ya tenia más uno nuevo. 

![prestacion_validada](https://user-images.githubusercontent.com/30004190/53414541-c2b0c180-39ad-11e9-8c34-dc363ee9af50.png)
![otro_diagnostico7](https://user-images.githubusercontent.com/30004190/53414542-c2b0c180-39ad-11e9-89fa-ac61b35a818a.png)
![auditar_prestacion](https://user-images.githubusercontent.com/30004190/53414546-c3495800-39ad-11e9-8a83-7d84e8ac37c0.png)
![dos_veces](https://user-images.githubusercontent.com/30004190/53414545-c2b0c180-39ad-11e9-9ebf-52d73c47419c.png)

**Comment by sychus** [comment]
solucionado
