### ISSUE TITLE
filtros en la HUDS de un paciente

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1111]
### Comportamiento actual
* Cuando visualizo la HUDS de un paciente, se ven mezclados los filtros de prestaciones y procedimientos
### Resultado esperado 
* Que los filtros de prestaciones y procedimientos respondan correctamente

### Pasos para reproducir el problema 
1. Ingresar a la HUDS de un paciente
2. Ir a Prestaciones/ Ir a Procedimientos
3. Visualizar la mezcla de filtros en ambos requerimientos

![image](https://user-images.githubusercontent.com/39344609/53428277-40ce9180-39c9-11e9-8d4b-00dfa2d50316.png)

**Comment by Silvinagabriela** [comment]
Al no interpretarse correctamente el Issue #1111 se resolvió el #792.
Se cierra y se vuelve a reportar en dos issues distintos #1277 y  #1278
