### ISSUE TITLE
RUP - Iniciar una prestación - agregar pacientes 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1114]
### Comportamiento actual
Al iniciar una prestación en RUP si el paciente no existe es necesario salir del modulo RUP y moverse al modulo MPI para empadronarlo

### Resultado esperado 
Se sugiere poder agregar pacientes nuevos desde la pantalla de búsqueda de pacientes para iniciar prestación.

### Pasos para reproducir el problema 
1. Iniciar prestación fuera de agenda
2. Buscar un paciente inexistente 
3. 
![image](https://user-images.githubusercontent.com/38788179/53565809-36cba080-3b39-11e9-9e35-1c646329cf66.png)

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
