### ISSUE TITLE
MPI: Notas 

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1123]
### Comportamiento actual
* A los pacientes que se les carga alguna "Nota" extensa en su validación, no es posible darle turno. 

### Resultado esperado 
* Que el sistema permita agregar notas extensas, en todo caso que se visualice en el header del paciente una parte del mismo.

### Pasos para reproducir el problema 
1. Cargar en MPI nota extensa a algún paciente
2. Ir a punto de inicio
3. intentar darle turno

![image](https://user-images.githubusercontent.com/39344609/53885851-7d1f7480-3ffd-11e9-9e02-20fc2e9f9538.png)

**Comment by palita1991** [comment]
Resuelto en la v4.5.0.
