### ISSUE TITLE
Gestor de usuarios

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1127]
### Comportamiento actual
* Al dar permisos en el gestor de usuarios para el modulo de Matriculaciones, hay 2 slider que no tienen nombre.

### Resultado esperado 
* Deberían mostrarse de forma adecuada para los usuarios. Por ejemplo, title: "Insertar turno".
### Pasos para reproducir el problema 
1. 
2. 
3. 

![image](https://user-images.githubusercontent.com/39344609/53971341-80892d80-40db-11e9-9980-38f43538785f.png)

**Comment by palita1991** [comment]
Se resuelve en v4.4.11.
