### ISSUE TITLE
No se visualizan las observaciones de los hallazgos y trastornos al momento validar una prestación y en el registro de la consulta en la HUDS.

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1137]
No se visualizan las observaciones de los hallazgos y trastornos al momento validar una prestación y en el registro de la consulta en la HUDS.

_Originally posted by @palita1991 in https://github.com/andes/app/pull/1130#issuecomment-472545530_

**Comment by palita1991** [comment]
Resuelto. Se cierra issue.
