### ISSUE TITLE
Acceso a Modulo desde URL sin permisos

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1147]
### Comportamiento actual
* Desde la URL https://app.andes.gob.ar/buscador, es posible ingresar al modulo "Buscador de turnos y prestaciones" sin tener el permiso que corresponde.

### Resultado esperado 
* Que no se pueda acceder al modulo si el usuario no tiene el permiso

### Pasos para reproducir el problema 
1. Desde gestionUsuarios tener deshabilitado el permiso "Buscador de turnos y prestaciones"
2. Ingresar a https://demo.andes.gob.ar/buscador
3. Notar que se puede acceder...

**Comment by sychus** [comment]
resuelto
