### ISSUE TITLE
Acceso a modulo Prestamos de carpetas desde URL sin permisos

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1149]
### Comportamiento actual
* Desde la URL https://app.andes.gob.ar/prestamosHC, es posible ingresar al modulo "Buscador de turnos y prestaciones" sin tener el permiso que corresponde.
* El path del routing y estructura de carpetas no respeta las convenciones establecidas en la [Guía de desarrollo](https://github.com/andes/andes/wiki/C%C3%B3digo-fuente#routing)

### Resultado esperado 
* Que el sistema no permita al acceso de modulo préstamo de carpetas sin tener el permiso correspondiente

### Pasos para reproducir el problema 
1. Desde gestionUsuarios tener deshabilitado el permiso "Prestamo de Carpetas"
2. Ingresar a https://demo.andes.gob.ar/prestamosHC
3. Notar el acceso a dicho modulo....

**Comment by lucasgonzalezm** [comment]
Se corrigió en el commit ef0dee6 que ya se encuentra en `master`.
