### ISSUE TITLE
Acceso a Modulo HUDS desde URL sin permisos

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1152]
### Comportamiento actual
* Desde la URL ~~https://app.andes.gob.ar/rup/buscaHuds~~  https://app.andes.gob.ar/rup/huds , es posible ingresar al modulo "HUDS de un paciente" sin tener el permiso que corresponde.
* El path del routing y estructura de carpetas no respeta las convenciones establecidas en la [Guía de desarrollo](https://github.com/andes/andes/wiki/C%C3%B3digo-fuente#routing)

### Resultado esperado 
* No permitir el acceso al modulo de HUDS de un paciente si no se tiene el permiso

### Pasos para reproducir el problema 
1. Desde gestionUsuarios tener deshabilitado el permiso "Modulo HUDS"
2. Ingresar a ~~https://app.andes.gob.ar/rup/buscaHuds~~  https://app.andes.gob.ar/rup/huds
3. Notar que se puede acceder desde la URL...

**Comment by NicoDino** [comment]
:heavy_check_mark: 

Verificado - es necesario un fix en el control de permisos al iniciar el componente hudsBusquedaPaciente

**Comment by palita1991** [comment]
Se resuelve en v4.4.11.
