### ISSUE TITLE
Dashboard/Citas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1156]
### Comportamiento actual
* Al filtrar por fecha (hasta el dia actual) se genera error en consola.

### Resultado esperado 
* 
### Pasos para reproducir el problema 
1. ingresar a https://app.andes.gob.ar/dashboard/citas
2. filtrar por fecha del primer dia del mes en curso hasta el dia actual
3. Abrir consola...

![image](https://user-images.githubusercontent.com/39344609/54993302-45726f80-4fa0-11e9-9697-4538138f2e51.png)

**Comment by sychus** [comment]
resuelto
