### ISSUE TITLE
Reportes: Fuera de agenda

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1206]
### Comportamiento actual
* Cuando atiendo un paciente fuera de agenda (desde RUP), luego en el módulo Reportes no se ven registrados esos pacientes, siempre que sean diagnosticos y no C2.
### Resultado esperado 
* Poder visualizar pacientes atendidos fuera de agenda

### Pasos para reproducir el problema 
1. Desde Rup, iniciar prestación a paciente fuera de agenda, validar.
2. Auditar al paciente fuera de agenda
3. En el modulo Reportes no se visualiza este paciente.

**Comment by palita1991** [comment]
Resuelto en la v4.4.13
