### ISSUE TITLE
TOP: Solicitudes desde RUP

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1207]
### Comportamiento actual
* Las solicitudes que se cargan desde RUP, no se visualizan en el modulo TOP
### Resultado esperado 
* Poder visualizar las solicitudes que el profesional carga desde RUP

### Pasos para reproducir el problema 
1.  RUP, dar turno autocitado a paciente
2. ir al modulo TOP,
3. Intentar  buscar al paciente recién cargado en RUP

**Comment by Silvinagabriela** [comment]
En demo funciona correctamente (Antes de reproducir, configurar las reglas para el mismo efector en el que se esta logueado)

![image](https://user-images.githubusercontent.com/38788179/57222994-fc6bfd00-6fda-11e9-8465-a216e30e98f4.png)

**Comment by milagrosn** [comment]
ejemplo : paciente de centenario se le da turno desde RUP para niño sano, no se visualiza en el modulo de solicitudes pero cuando genero solicitud directamente desde el modulo si se visualiza. Estan las reglas dadas!

**Comment by Silvinagabriela** [comment]
Actualmente el modulo  solicitudes solo muestra las solicitudes de turnos pendientes.
