### ISSUE TITLE
Campaña Salud: cuerpo

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/app#1208]
### Comportamiento actual
Se está permitiendo pegar contenido en el cuerpo de la campaña de salud como así también agregar imágenes.

### Resultado esperado 
No permitir pegar contenido (hay una función de Javascript que hace esto) ni las imágenes

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by palita1991** [comment]
Se cierra, funcionamiento correcto. Se puede poner imágenes al copiar texto que incluye imágenes y pegarlo en el cuerpo de la campaña. Si bien no era lo que se buscaba, se muestra bien en la aplicación móvil y si el usuario no desea que no tenga imágenes que no la ponga.
