### ISSUE TITLE
Clonación de agendas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1215]
### Comportamiento actual
Muestra conflicto al clonar agendas cuando no lo hay.

### Resultado esperado 
mostrar conflicto solo cuando se repite espacio o profesional.

![image](https://user-images.githubusercontent.com/38788179/56976188-c21cde80-6b48-11e9-8c9f-5e48bd1f725a.png)
![image](https://user-images.githubusercontent.com/38788179/56976205-cba64680-6b48-11e9-80ad-4e45361264d2.png)

**Comment by lucasgonzalezm** [comment]
No se puede reproducir más el issue
