### ISSUE TITLE
RUP - insumo como diagnóstico principal

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1216]
### Comportamiento actual
Permite validar una prestación seleccionando un insumo como procedimiento/diagnóstico principal.

### Resultado esperado 
Preguntar solo cuando se trata de un hallazgo, un trastorno o un procedimiento. 

![image](https://user-images.githubusercontent.com/38788179/56983496-27c59680-6b5a-11e9-88b4-e00b21d71300.png)

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
