### ISSUE TITLE
RUP: Curva de la Evaluación de RCV

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1223]
### Comportamiento actual
* Cuando inicio prestación a paciente y veo en el "Resumen del paciente" la curva de "Evaluación de riesgo cardiovascular", no se visualiza la misma y me muestra el ultimo registro de ese concepto. 

### Resultado esperado 
* Visualizar la curva

### Pasos para reproducir el problema 
1. Iniciar prestación a paciente que tenga cargados RCV ir al "Resumen del paciente",
2. Notar  que la curva de RCV no se muestra y esta cargada el ultimo registro de RCV
3. 

![image](https://user-images.githubusercontent.com/39344609/57231152-5925e280-6ff0-11e9-88ac-229c403e4ef7.png)

**Comment by lucasgonzalezm** [comment]
Se cierra este issue porque Laura Monteverde dice que no es necesario. Nunca se mostró esta curva que se pide, de necesitarla se cargará más adelante como una user story
