### ISSUE TITLE
CITAS: Boton fuera de lugar

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1224]
### Comportamiento actual
* El botón "Volver" de la app web no se desplaza al final del listado sino que se superpone.
en campañas de salud ya se arreglo algo similar.

### Resultado esperado 
* Que el botón no se superponga en el listado de pacientes

### Pasos para reproducir el problema 
1. Ir a revisión de alguna agenda dinámica (con varios pacientes)
2. ver el listado y al scrolear visualizar que el boton "Volver" queda superpuesto
3. 

![image](https://user-images.githubusercontent.com/39344609/57231589-292b0f00-6ff1-11e9-854c-aa0e7ee1ffcc.png)

**Comment by andrrrl** [comment]
![63348552-d40cd200-c32f-11e9-9347-60d9eee11c3f](https://user-images.githubusercontent.com/11394455/63348765-5b5a4580-c330-11e9-836d-aac95b4a7a9f.png)
por qué la agresión?

**Comment by palita1991** [comment]
Se arregla en #1381
