### ISSUE TITLE
Dashboard: Cambio de tipo de turno

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1227]
### Comportamiento actual
* Cambiar nombre en tipo de turno "Gestión" por "Con llave"

### Resultado esperado 
* ¿Que espera que suceda?

### Pasos para reproducir el problema 
1. Ir a dashboard, filtrar por tipo de turno y un rango de fecha
2. visualizar tipo de turno de gestion...
3. 

![image](https://user-images.githubusercontent.com/39344609/57236285-1584a600-6ffb-11e9-8205-a43f74752dee.png)

**Comment by NicoDino** [comment]
Resuelto en PR Dashboard PR #1221

**Comment by andrrrl** [comment]
![image](https://user-images.githubusercontent.com/11394455/64191079-1107b700-ce4e-11e9-9a6d-42c23d5bd244.png)
Resultado inception @NicoDino

**Comment by palita1991** [comment]
Se cierra, resuelto en PR #1221
