### ISSUE TITLE
Gestor de usuario: editar nombre de agrupación

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1228]
### Comportamiento actual
* Resumen del problema.

### Resultado esperado 
* ¿Que espera que suceda?

### Pasos para reproducir el problema 
1. 
2. 
3. 

![image](https://user-images.githubusercontent.com/39344609/57242467-efb2cd80-7009-11e9-8fcc-f5c79011f72f.png)

**Comment by lucasgonzalezm** [comment]
Ya subí la corrección a este issue.
