### ISSUE TITLE
MPI(NV) - paciente temporal bebe - guardar

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1229]
### Comportamiento actual
Al crear un paciente bebe y guardar, el botón no muestra respuesta pero guarda el paciente. si se clickea x veces guarda esa cantidad de veces el paciente. 
(esto no sucede si se escanea una relación con un paciente ya validado)
### Resultado esperado 
Guardar solo un paciente, devolver a la pantalla de búsqueda

### Pasos para reproducir el problema 
1. crear un paciente temporal - bebe
2. cargar los siguientes datos: Nombre apellido sexo y fecha de nacimiento
3. hacer clic en guardar
![image](https://user-images.githubusercontent.com/38788179/57247774-1c211680-7017-11e9-8fbc-1d69a63dc3ef.png)

**Comment by NicoDino** [comment]
Sigue pasando en v 450 test  pendiente de fix!

**Comment by milagrosn** [comment]
Resuelto!!
