### ISSUE TITLE
MPI(NV) - Escaneo en relaciones

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1232]
### Comportamiento actual
Al generar un paciente temporal (bebe) y escanear en el campo de relaciones el DNI de un paciente que no fue previamente validado en el sistema, tira un error 

### Resultado esperado 
Cuando el paciente que se intenta escanear no existe registrado en el sistema
**Propuesta**
1 - mostrar un alerta que indique al usuario lo que tiene que hacer (Ej: registrar previamente al paciente que se quiere relacionar) - esta opción puede generar que no se realicen vinculaciones entre pacientes ya que sería un proceso engorroso. 
2-**Propuesta para US**  si se escanea un DNI tomarlo como paciente validado y guardarlo en la base con los datos que trae el DNI (en otra oportunidad se completara el resto de los datos) - 
3 - **Propuesta para US** guardar en el paciente la relación como temporal sin que esta relación se guarde en la base, simplemente tomar los datos DNI, nombre, apellido e indicar el tipo de relación

### Pasos para reproducir el problema 
1. Crear un paciente temporal (bebe)
2. Escanear en relaciones un DNI que no se encuentre registrado en el sistema
3. hacer clic sobre el paciente escaneado para ingresarlo
4. error 

![image](https://user-images.githubusercontent.com/38788179/57296770-305f2500-70a4-11e9-894a-95dadb8bc6f5.png)
![image](https://user-images.githubusercontent.com/38788179/57296787-3bb25080-70a4-11e9-91a2-14bba42c6922.png)

**Comment by NicoDino** [comment]
fixeado en v450 subido a test
