### ISSUE TITLE
MPI(NV) - Paciente temporal con DNI- validar con RENAPER

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1234]
### Comportamiento actual
al buscar un paciente temporal con DNI y validarlo, no permite hacerlo. Es necesario modificar algún dato para que el botón se active

### Resultado esperado 
si el paciente tiene datos correctos poder validar con RENAPER

### Pasos para reproducir el problema 
1. Buscar un paciente ya registrado temporal con DNI
2. ingresar para editarlo
3. no editar nada, solo hacer clic en botón validar (no permite)

**Comment by NicoDino** [comment]
funcionando en test v4.5.0
