### ISSUE TITLE
CITAS - Clonación de agendas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1237]
### Comportamiento actual
Cuando se clona una agenda sobre otra con el mismo horario y profesionales pero distintas prestaciones, pueden clonarse y publicarse. 

### Resultado esperado 
Cuando clono agendas en las que se superpongan horarios y profesionales no debería permitir clonar
### Pasos para reproducir el problema 
1. Se busca en el gestor de agendas dos agendas con profesional ya creadas en estado "planificación", una para el lunes y otra para el martes, ambas con el mismo horario. 
2. seleccionar la del día lunes y clonarla para el martes.
3. permite clonar sin mostrar conflicto

**Comment by palita1991** [comment]
Se resuelve en v4.4.11.
