### ISSUE TITLE
CITAS - Clonación de agendas - días del calendario

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1238]
### Comportamiento actual
Al momento de clonar una agenda, en el calendario, en los meses **septiembre y diciembre** no se visualiza el día 1° del mes

### Resultado esperado 
Ver el mes completo

### Pasos para reproducir el problema 
1. seleccionar una agenda 
2. clonarla para el mes de septiembre o diciembre
3. no figura el 1er día del mes

**Comment by lucasgonzalezm** [comment]
Se cierra porque ya se cargó en #1194
