### ISSUE TITLE
HUDS: Evolución de un concepto Snomed no actualiza fecha

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1240]
### Comportamiento actual
* Cuando reviso la HUDS de un paciente , al seleccionar un concepto que tiene varias evoluciones, y navego por las mismas de ese concepto no se actualiza en simultáneo los datos de la prestación en donde se hizo esa evolución y sólo figura los datos de la primer prestación es decir la fecha en donde se cargó ese concepto por primera vez.
### Resultado esperado 
* ¿Que espera que suceda?
Que al seleccionar un concepto que tiene varias evoluciones cuando navego por las mismas también se debe cambiar  la fecha con los correspondientes datos de la prestación en donde se evolucionó tal concepto.
### Pasos para reproducir el problema 
1. Ingreso a la HUDS de un paciente que tenga evoluciones de un mismo concepto por ejemplo el trastorno hipertensión arterial 
2. Navego por las fechas de las evoluciones de este concepto (y si me permite visualizarlas)
3. Visualizar que no se cambian en simultáneo los datos de la prestación de esas evoluciones y sólo figura la primer prestación en donde se cargó ese concepto.

Agustina Molini

![image](https://user-images.githubusercontent.com/39344609/57375728-8d2a1080-7174-11e9-867e-cc2739adb085.png)

![image](https://user-images.githubusercontent.com/39344609/57375819-c9f60780-7174-11e9-815f-9055c27f0607.png)

**Comment by palita1991** [comment]
Resuelto en la v4.4.13
