### ISSUE TITLE
HUDS: No se visualiza fármaco/s en "datos de la prestación" de una evolución

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1243]
### Comportamiento actual
*  Al visualizar evoluciones de un concepto,  en datos de la prestación no figuran los fármacos/insumos con el color del ícono correspondiente (aparece un casillero blanco y sólo al hacer doble click se visualiza)

### Resultado esperado 
* Que al abrir una evolución en los datos de la prestación se puedan visualizar los fármacos/insumos (con el color correspondiente a su ícono)

### Pasos para reproducir el problema 
1. Visualizar HUDS  de un paciente, y seleccionar un trastorno con varias evoluciones que tengan fármacos /insumos cargados
2. Ver datos de la prestación de tal evoluciones  y visualizar que en algunos casos que hay casilleros vacíos en donde debería figurar el insumo/fármaco con su color correspondiente
3.Sólo se pueden ver los insumos haciendo doble click en ese espacio vacío.

Ref. Agustina Molini

![image](https://user-images.githubusercontent.com/39344609/57379499-68866680-717d-11e9-9ed3-9c0eedc8d248.png)

![image](https://user-images.githubusercontent.com/39344609/57379535-7936dc80-717d-11e9-97b7-f01d224cd9e3.png)

**Comment by milagrosn** [comment]
Resuelto en v 4.4.11

**Comment by lucasgonzalezm** [comment]
Se reabre este issue porque no está resuelto. Todavía sucede con algunos fármacos. Cuando se cerró se probó con unos que justo se mostraban bien

![WhatsApp Image 2019-06-06 at 10 30 12](https://user-images.githubusercontent.com/18200503/59039905-1142e700-884c-11e9-8d94-b4b96f199519.jpeg)
![WhatsApp Image 2019-06-06 at 10 30 36](https://user-images.githubusercontent.com/18200503/59039916-19028b80-884c-11e9-90fa-56eec0f9824a.jpeg)
----
![WhatsApp Image 2019-06-06 at 10 34 35](https://user-images.githubusercontent.com/18200503/59039930-1bfd7c00-884c-11e9-9c70-3d1abd2175ae.jpeg)
![WhatsApp Image 2019-06-06 at 10 35 05](https://user-images.githubusercontent.com/18200503/59039933-1dc73f80-884c-11e9-946a-d13845d9deca.jpeg)

**Comment by lucasgonzalezm** [comment]
Se cierra porque se corrigió en 82078f8 que se mergeó a la versión `v4.5.1`
