### ISSUE TITLE
GESTIÓN USUARIOS - Copiar permisos

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1246]
### Comportamiento actual
Cuando quiero copiar los permisos de un efector a otro no se copian, solo se agrega el efector

### Resultado esperado 
Al copiar permisos, se debe agregar el efector con los mismo permisos del efector copiado

### Pasos para reproducir el problema 
1. Ingresar al gestor de usuarios
2. seleccionar un efector
3. hacer click en copiar
4. buscar efector para copiar
5. agregar.

**Comment by lucasgonzalezm** [comment]
Corregido en #1173
