### ISSUE TITLE
GESTIÓN USUARIOS - Gestor de usuarios

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1247]
### Comportamiento actual
Si a un usuario con permisos para el gestor, le quito la posibilidad de agregar efectores (o cualquiera de los permisos anidados) Este lo puede volver a habilitar 

### Resultado esperado 
Si al momento de habilitar un usuario para que de permisos, le deshabilito algunos permisos de los anidados, que el usuario no pueda activarlos.

### Pasos para reproducir el problema 
1. como usuario, desde un efector habilitar permisos como gestor de usuario en otro efector
2. deshabilitar algunas opciones
3. guardar
4. ingresar en ese otro efector
5. se puede volver a habilitar el permiso. 

![image](https://user-images.githubusercontent.com/38788179/57392611-a4c6c080-7197-11e9-8ac2-236eac82b1c8.png)

**Comment by lucasgonzalezm** [comment]
Lo cierro porque pasa como US ya que es una mejora
