### ISSUE TITLE
GESTIÓN USUARIOS - mensaje al pausar efector

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1249]
### Comportamiento actual
el mensaje al pausar un efector dice pausar "usuario"

### Resultado esperado 
El mensaje debe decir "¿esta seguro que desea pausar los permisos para este efector?" cancelar confirmar 

### Pasos para reproducir el problema 
1. 
2. 
3. 

![image](https://user-images.githubusercontent.com/38788179/57394629-5c5dd180-719c-11e9-9945-cd2e8fabe131.png)

**Comment by lucasgonzalezm** [comment]
Se resuelve en branch `usuarios2.0` #1173 commit 62a4613
