### ISSUE TITLE
MPI (NV) - marcar un punto en el mapa

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1258]
### Comportamiento actual
*Al marcar un punto en el mapa y guardar, este cambio no se guarda

### Resultado esperado 
Indicar un punto en el mapa y que este cambio queda guardado

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by NicoDino** [comment]
sigue asi en v4.5.0

**Comment by NicoDino** [comment]
solved
