### ISSUE TITLE
CITAS: Agendas que no se Auditan

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1259]
### Comportamiento actual
* Cuando suspendo un turno, la agenda no se puede auditar si no reasigno el turno, y no siempre quiero reasignar el turno.

### Resultado esperado 
* Poder auditar una agenda que tiene turno/s suspendidos sin tener que reasignar, 

### Pasos para reproducir el problema 
1. Dado un turno , lo suspendo
2. Pasada la fecha de la agenda, audito todos los pacientes menos el suspendido 
3. Visualizar que la agenda no queda auditada

![Uploading image.png…]()

**Comment by lucasgonzalezm** [comment]
Se cierra porque no se puede reproducir

**Comment by milagrosn** [comment]
No se puede reproducir?

**Comment by milagrosn** [comment]
![Uploading image.png…]()

**Comment by milagrosn** [comment]
![Uploading image.png…]()

**Comment by plammel** [comment]
@palita1991 @lucasgonzalezm @milagrosn  Este caso parece ser una mejora más que un issue. Es necesaria una user story para definir cual debiera ser la interacción en este caso (¿Cómo se realiza la auditoria, manual o automática? ¿Si se aprueban diagnósticos, como audito un turno suspendido que no posee diagnósticos que aprobar? etc..)

**Comment by Silvinagabriela** [comment]
Se cierra, se pasa a US.
