### ISSUE TITLE
MPI (NV) - Indicar tipo de relación 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1260]
### Comportamiento actual
Al indicar el tipo de relación este dato no queda guardado 

### Resultado esperado 
una vez guardados los datos del paciente visualizar el tipo de relación ingresado

### Pasos para reproducir el problema 
1. a un paciente agregar relación e indicar tipo
2. guardar
3. buscar nuevamente al paciente
4. ver el tipo en la solapa relaciones. 

![image](https://user-images.githubusercontent.com/38788179/57540739-c359c280-7323-11e9-8eb6-0e6175e2a4d5.png)

**Comment by NicoDino** [comment]
solucionado en v 4.5.0
