### ISSUE TITLE
MPI(NV): fecha de nacimiento se carga en campo DNI

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1262]
### Comportamiento actual
* Cuando cargo un nuevo paciente extranjero al darle un turno, la fecha de nacimiento se visualiza en el campo de DNI
### Resultado esperado 
* Poder ver los campos donde corresponden

### Pasos para reproducir el problema 
1. Generar paciente extranjero nuevo
2. Darle un turno
3. Visualizar en el sidebar los campos DNI y Fecha de nacimiento

![image](https://user-images.githubusercontent.com/39344609/57626682-c398ce80-756c-11e9-9071-2b806aa26d92.png)

**Comment by NicoDino** [comment]
solved v4.5.0
