### ISSUE TITLE
CITAS - Espacios físicos inactivos

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1275]
### Comportamiento actual
El sistema permite crear agendas con espacios físicos inactivos

### Resultado esperado
 No mostrar en el combo de espacios físicos consultorios inactivos.

### Pasos para reproducir el problema 
1. en configuración de espacios inactivar un espacio físico
2. crear una agenda con ese espacio físico 
3. 

![image](https://user-images.githubusercontent.com/38788179/57779526-9d099d80-76fc-11e9-8092-728f49db990e.png)

![image](https://user-images.githubusercontent.com/38788179/57779379-5a47c580-76fc-11e9-9f4f-08abed66eaea.png)

**Comment by palita1991** [comment]
SUGERENCIA 
- Agregar filtro en la api
- Enviar filtro desde la app.
