### ISSUE TITLE
RUP: HUDS - Al filtrar por categoría los conceptos no se muestran correctamente

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#1278]
### Comportamiento actual
En la HUDS del paciente, al filtrar por la categoría procedimientos se visualizan solicitudes

### Resultado esperado 
Mostrar los conceptos que corresponden a la categoría filtrada

### Pasos para reproducir el problema 
1. Partir de una prestación validada que contenga solicitudes y procedimientos 
2. Visualizar la HUDS del paciente
3. Observar que filtrando por procedimientos muestra conceptos de la categoría solicitudes. 

![Sin título](https://user-images.githubusercontent.com/38788179/57785090-6ab16d80-7707-11e9-8ab9-d0bb6c0284aa.png)

**Comment by palita1991** [comment]
@silviroa Se quiere un análisis de este issue.

**Comment by lucasgonzalezm** [comment]
Se cierra porque se va a pasar como una mejora (US). Todavía no está bien definido como será, pero se cree que se agregará el filtro de Solicitudes y habrá que modificar el comportamiento actual de Procedimientos para que no traiga más las solicitudes.
