### ISSUE TITLE
CItas: Agendas No Nominalizadas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1298]
### Comportamiento actual
* El sistema permite desde RUP crear un "Fuera de agenda" con prestación No nominalizada (Act. con la comunidad y Act. con la organización) para un profesional que ya tiene una agenda en el mismo horario generada desde gestión.

### Resultado esperado 
* Que no me permita armar una agenda No nominalizada en un rango de horario que el profesional ya tiene agenda armada.

### Pasos para reproducir el problema 
1. Tener armada una agenda para profesional X de 10 a 12 hs para medicina general
2. Desde RUP el profesional X arma un fuera de agenda para la prestación Act. con la comunidad con el horario de 10 a 12 hs
3. Notar que es posible armar esa agenda y se superpone con el punto 1

**Comment by lucasgonzalezm** [comment]
Se pasa como una mejora
