### ISSUE TITLE
CITAS: error consola creación de agenda, seleccionar prestación

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/app#1315]
### Comportamiento actual
* Resumen del problema.
Al momento de crear una nueva agenda, al seleccionar la prestación salta en consola el error que se muestra en la captura de pantalla.

### Resultado esperado 
* ¿Qué espera que suceda?
Que no salga ningún error en consola al cargar prestaciones para la agenda.
### Pasos para reproducir el problema 
1. Ir al gestor de agendas
2. Seleccionar la opción de crear una agenda
3. Abrir la consola con F12
4. Seleccionar cualquier prestación y se carga el error de la captura

![image](https://user-images.githubusercontent.com/18200503/58565065-753e2d80-8204-11e9-8309-35d7db4589a7.png)

**Comment by milagrosn** [comment]
No se puede reproducir!
