### ISSUE TITLE
CITAS: Agendas con mismo profesional y horario

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1320]
### Comportamiento actual
* Es posible crear agendas con el mismo profesional y horario cuando la conectividad es lenta. 

### Resultado esperado 
* No poder crear agendas para un profesional ya asignado en otra agenda con el mismo horario

### Pasos para reproducir el problema 
1. Crear una agenda para un profesional "X" en horario "Y"
2. Con conectividad lenta, crear otra agenda para mismo profesional misma hora
3. Notar que el sistema lo permite

![image](https://user-images.githubusercontent.com/39344609/58803048-f458aa80-85e4-11e9-8793-1d4239ab6106.png)

**Comment by plammel** [comment]
Este issue se produce debido a que la validación de solapamiento se efectúa al momento de asignar al profesional. Existe un gap entre la validación y el request de POST/PUT, en el pudieran generarse en la base de datos las condiciones de solapamiento y la app realizar request a la api sin advertir dichas actualizaciones de datos. La solución a implementar es efectuar una validación de solapamiento en la api, justo previo al POST/PUT de agenda.
@lucas-gonzalez @palita1991 @kroce , por favor indicar cuales debe de ser los criterios de esta validación o referenciar la user storie donde se detallen dichos criterios.

**Comment by palita1991** [comment]
En este issue se resolvió lo mismo para la clonación de agendas. Explica los casos que debe pasar y cuáles no.
#1181
Los conflictos con espacios físicos tienen el mismo criterio que con los profesionales
