### ISSUE TITLE
CITAS: Espacio fisico

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1322]
### Comportamiento actual
* Es posible crear mas de una agenda con el mismo espacio físico para el mismo horario, debido a la baja conectividad.
### Resultado esperado 
* Si la conectividad es pobre, que el sistema no me permita usar el mismo espacio fisico para una agenda
### Pasos para reproducir el problema 
1. Crear una agenda con espacio físico "X"
2. Con lenta conectividad: crear otra agenda con el mismo espacio físico
3. Notar que es posible

![image](https://user-images.githubusercontent.com/39344609/58809799-fd507880-85f2-11e9-81cb-b0c34ff0c837.png)

**Comment by plammel** [comment]
Este issue se produce debido a que la validación de solapamiento se efectúa al momento de asignar el espacio físico. Existe un gap entre la validación y el request de POST/PUT, en el pudieran generarse en la base de datos las condiciones de solapamiento y la app realizar request a la api sin advertir dichas actualizaciones de datos. La solución a implementar es efectuar una validación de solapamiento en la api, justo previo al POST/PUT de agenda.
@lucas-gonzalez @palita1991 @kroce , por favor indicar cuales debe de ser los criterios de esta validación o referenciar la user storie donde se detallen dichos criterios.
