### ISSUE TITLE
RUP - Modulo Solicitudes 

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#1323]
### Comportamiento actual
Al generar una solicitud desde RUP esta no se visualiza en la bandeja de entrada del modulo solicitudes.

### Resultado esperado 
Ver solicitudes generadas desde RUP para poder asignar el turno con llave 

### Pasos para reproducir el problema 
1. Ingresar al modulo solicitudes
2. Configurar las reglas para el mismo efector en el que esta logueado (elegir una prestación Ej: consulta de control de embarazo de alto riesgo, indicar como efector destino el mismo efector en el que esta logueado, seleccionar una prestación origen Ej. Consulta de control de embarazo)
3. Una vez configuradas las reglas entrar en RUP
4. Iniciar prestación fuera de agenda con la prestación origen (Consulta de control de embarazo)
5. En el buscador Snomed ingresar el concepto "consulta de control de embarazo de alto riesgo" 
6.agregarlo a la consulta filtrando con la categoría "solicitud"
7. guardar y validar
8. ingresar en el modulo solicitudes - bandeja de entrada
9. no se ve la solicitud ingresada.

**Comment by palita1991** [comment]
Pasa a mejora según el análisis entre @negro89 y @silviroa . Falta decidir cuales son las solicitudes que se deberían mostrar en el módulo solicitudes.
