### ISSUE TITLE
CITAS - Dar turno en Agendas dinámicas - actualizar sidebar

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/app#1332]
### Comportamiento actual
* Resumen del problema.
No se actualiza el sidebar en agendas dinámicas cuando se presiona el botón "agregar paciente"
### Resultado esperado 
* ¿Que espera que suceda?
Que se actualice los datos del sidebar siempre que se modifica la selección de la agenda.

### Pasos para reproducir el problema 
1. crear una agenda dinámica y publicarla
2. ingresar en RUP
3. iniciar una prestación fuera de agenda para un paciente
4. agregarle un concepto
5. guardar y validar
6. volver al punto de inicio
7. hacer clic en la agenda dinámica creada
8. hacer clic en el botón agregar paciente
9. hacer clic en pacientes fuera de agenda
10. no se actualiza el sidebar con la descripción de la agenda

![image](https://user-images.githubusercontent.com/18200503/59106446-c9d05f80-890c-11e9-8025-ae52a990c481.png)

**Comment by negro89** [comment]
Al seleccionar las distintas agendas el sidebar se actualiza normalmente pero cuando se presiona el botón de agregar un paciente aparecen los botones "cancelar" y "guardar" lo que significa que uno debe confirmar o detener la acción (De agregar un paciente). Por lo tanto estaría bien que no se actualice el sidebar en este momento.

Por otro lado:
- Al buscar un paciente, si la lista de resultados es muy extensa el usuario debe scrollear hasta el final de la lista para cancelar o guardar ya que los botones no están posicionados en un lugar fijo.
- Si buscando un paciente hacemos click en otra agenda, aunque el sidebar no se actualice, luego al presionar "cancelar" se visualiza la agenda que clickeamos recientemente en lugar de en la que estabamos trabajando. No podría ser confuso?
- Si se selecciona un paciente de los resultados de búsqueda y luego se realiza una nueva, el resultado anterior permanece.

Quizás se pueda proponer como una mejora?

**Comment by lucasgonzalezm** [comment]
@andrrrl @JSantarelli qué hacemos con esto? Nos pueden dar una mano?

**Comment by andrrrl** [comment]
>     * Al buscar un paciente, si la lista de resultados es muy extensa el usuario debe scrollear hasta el final de la lista para cancelar o guardar ya que los botones no están posicionados en un lugar fijo.

Claramente, este problema es de experiencia de usuario (UX). Por algunas modificaciones que tienen que ver con la navegabilidad, se determinó que todos los footers se van a eliminar, con lo cual la regla general es que no haya (puede haber alguna excepción) botones al final de una lista, de un componente o de una pantalla. La solución sería tener los botones en el tope superior de la lista, fijos (que no hagan scroll).
También habría que ver si esta tarea corresponde dentro de este mismo issue, o si hay que hacer otro aparte.

**Comment by andrrrl** [comment]
>     * Si buscando un paciente hacemos click en otra agenda, aunque el sidebar no se actualice, luego al presionar "cancelar" se visualiza la agenda que clickeamos recientemente en lugar de en la que estabamos trabajando. No podría ser confuso?

También es un tema de UX. Un criterio más acertado sería que si se está dentro de un contexto de acciones A (viendo la agenda 1), al hacer click en un elemento B (la agenda 2), el contexto pase a B. Es decir se cierra y cancela todo lo que se estaba haciendo en A y se visualiza el contexto B.

**Comment by andrrrl** [comment]
>     * Si se selecciona un paciente de los resultados de búsqueda y luego se realiza una nueva, el resultado anterior permanece.

También de UX. Debería limpiarse el resultado ante una búsqueda nueva, luego de que el paciente ya fue seleccionado.
