### ISSUE TITLE
TOP - Error al crear una solicitud sin la regla necesaria

### ISSUE THREAD

**Issue by lucasgonzalezm** [andes/app#1338]
### Comportamiento actual
* Resumen del problema.
Al momento de crear una solicitud de salida, los `plex-select` muestran prestaciones que no aparecen en las reglas.
### Resultado esperado 
* ¿Qué espera que suceda?
Que coincida la información mostrada tanto en el momento de crear una solicitud como al ver las reglas.
Supongo que el bug está al momento de crear la solicitud.

Los `plex-select` se deben ir cargando las opciones a medida que se vayan seleccionando una opción en los `plex-select` anteriores.
Para el caso de una nueva solicitud de **entrada**:
- Los tipos de prestación solicitada deben estar cargados al entrar a la página, habiendo filtrado por las reglas con organización destino = organización donde el usuario esté logueado.
- La organización origen debe mostrar las opciones filtrando de las reglas aquellas que cumplan con el destino seleccionado (organización y prestación)
- Por último, el tipo de prestación origen se carga al seleccionar los dos filtros anteriores

Para el caso de una nueva solicitud de **salida** es igual salvo que cambiando lo que es origen por destino:
- Los tipos de prestación origen deben estar cargados al entrar a la página, habiendo filtrado por las reglas con organización origen = organización donde el usuario esté logueado.
- La organización destino debe mostrar las opciones filtrando de las reglas aquellas que cumplan con el origen seleccionado (organización y prestación)
- Por último, el tipo de prestación destino se carga al seleccionar los dos filtros anteriores

### Pasos para reproducir el problema 
En la base de datos de demo, logueado en Hospital Plottier
1. Ir al módulo de solicitudes (menú hamburguesa)
2. Seleccionar el botón Reglas global
3. Cargar en los filtros:
  - Efector origen: Hospital Plottier
 - Prestación origen: consulta de medicina general
 - Efector destino: Hospital Castro Rendón
![image](https://user-images.githubusercontent.com/18200503/59293611-ed214480-8c55-11e9-822c-70ecf6412085.png)
4. Ver los resultados de la búsqueda que solo trae la prestación destino consulta de oncología
5. Para crear una nueva solicitud, ir a la página anterior con el botón Volver
6. Seleccionar la pestaña de Solicitudes de Salida
7. Seleccionar el botón Nueva solicitud
8. Seleccionar un paciente cualquiera
9. Cargar Tipo de prestación origen: consulta de medicina general
10. Cargar Organización destino: Castro Rendón
11. Clickear la prestación destino y ver que aparecen más opciones de las que se mostraban en la pantalla de reglas globales.
![Selection_003](https://user-images.githubusercontent.com/18200503/59295134-5191d300-8c59-11e9-943d-df4dd6fbb703.png)

**Comment by lucasgonzalezm** [comment]
Aprovechando que se toca estas pantallas, estaría bueno modificar el orden en el formulario para crear una nueva solicitud de entrada.
En esta imagen comparo la solicitud de entrada con la de salida. La de salida está mejor organizada. La de entrada debería seguir el orden de las de salida. Esto significa que profesional destino debería quedar justo después de Tipo de prestación solicitada

![image](https://user-images.githubusercontent.com/18200503/59373739-a6e4e780-8d20-11e9-8e93-15c798095676.png)

**Comment by plammel** [comment]
El problema se debe a la falta del parámetro de organización destino en el GET de reglas. El problema quedaría corregido con el merge de #1390. 
De todas formas, realizando tests encontré un nuevo error: Cuando se selecciona una prestación destino y luego se borra la organización destino, la prestación destino queda seleccionada. Al seleccionar una nueva organización destino, la prestación destino permanece seleccionada y se mezcla en el combo con las prestaciones correspondientes a la nueva organización destino seleccionada, pudiendo así crear una solicitud que no está habilitada por las reglas TOP.
Presumiblemente este es un error de PLEX, ya que probé nullear explicitamente el model del select en el componente y el atributo efectivamente queda nulo, pero la selección del select permanece (no la limpia).

**Comment by palita1991** [comment]
Se cierra, el PR que lo soluciona ya esta mergueado
