### ISSUE TITLE
CITAS - Layout en revisión de agendas

### ISSUE THREAD

**Issue by silviroa** [andes/app#1355]
### Comportamiento actual
* Cuando se ingresa a la revisión de una agenda el botón volver no se ve correctamente

### Resultado esperado 
* Que el botón volver se vea en el footer de la pantalla

### Pasos para reproducir el problema 
1. Ingresar al gestor de agenda
2. Buscar una agenda pendiente de auditoria
3. Ingresar a la revisión

![image](https://user-images.githubusercontent.com/11513044/60022538-65cacc80-966a-11e9-98bd-47203031a9f2.png)

**Comment by palita1991** [comment]
Se cierra porque está cargado en el issue https://github.com/andes/app/issues/1224 .
