### ISSUE TITLE
Prestamos de Carpeta: Solicitud Manual

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1365]
### Comportamiento actual
* Cuando quiero generar una solicitud manual, el botón ( + ) no responde
### Resultado esperado 
* Poder generar una solicitud manual

### Pasos para reproducir el problema 
1. Ir  a Modulo Prestamos de carpetas 
2. Intentar abrir una solicitud manual
3. Notar que no se realiza ninguna acción, tampoco se genera error en consola

![image](https://user-images.githubusercontent.com/39344609/60589012-c8108500-9d6e-11e9-83b5-a291c23e5d10.png)

**Comment by palita1991** [comment]
Se cierra, se arregla en PR https://github.com/andes/app/pull/1396
