### ISSUE TITLE
PI RUP: Sobreturnos muestran "Ver resumen"

### ISSUE THREAD

**Issue by kroce** [andes/app#1380]
### Comportamiento actual
* En el punto de inicio de Consultorio cuando una agenda tiene sobreturnos con una prestación asociada, se está visualizando el botón "Ver Resumen" para todos los profesionales que tienen acceso a esa agenda.

### Resultado esperado 
* En el punto de inicio de Consultorio cuando una agenda tiene sobreturnos con una prestación asociada sólo el profesional que ejecutó y valido la prestación debería tener acceso a la misma.

### Pasos para reproducir el problema 
1. Crear una agenda para Consulta de Medicina General
2. Asignarle un sobreturno
3. Ingresar al punto de inicio de RUP
4. Iniciar y validar una prestación en el sobreturno asignado
5. Ir al punto de inicio con otro profesional con permisos para Consulta de Medicina General

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1401
