### ISSUE TITLE
PI Citas: turnos en agendas sin profesionales

### ISSUE THREAD

**Issue by silviroa** [andes/app#1382]
### Comportamiento actual
Cuando se crea una agenda con profesional asociado y antes de publicarla se la edita quitando el/los profesionales asociados, al dar un turno para dicha agenda desde el punto de inicio se produce un error al mostrar el turno en el histórico de turnos del paciente

### Resultado esperado 
Que se pueda dar un turno en una agenda sin profesionales asignados y se visualice el turno en el histórico de turnos

### Pasos para reproducir el problema 
1. Crear una agenda sin profesionales asignados
2. Editar la agenda (en planificación) asociando y luego eliminando lo profesionales de la agenda.
3. Publicar la agenda
4. Dar un turno desde el punto de inicio para la agenda publicada.

**Comment by NicoDino** [comment]
Refactorizar también para que las agendas generadas sin profesionales sean siempre iguales.
Ahora puede pasar que la key profesionales sea null o []

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1383
