### ISSUE TITLE
CITAS: Turnos para pacientes temporales sin DNI

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1386]
### Comportamiento actual
* Se muestra ventana de error al dar turno a un paciente temporal sin DNI

### Resultado esperado 
* Poder dar el turno a pacientes temporales sin estos mensajes de error

### Pasos para reproducir el problema 
1. Dar turno a paciente temporal sin DNI
2. Visualizar ventana de error
3. 

![image](https://user-images.githubusercontent.com/39344609/62145998-d6e54b80-b2ca-11e9-8d1d-132227d1bb8c.png)

**Comment by palita1991** [comment]
Resuelto en https://github.com/andes/app/pull/1387 . Ya está en producción.
