### ISSUE TITLE
CITAS: agenda con turno suspendido no permite auditar agenda

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1388]
### Comportamiento actual
* En una agenda con pacientes; suspendo un turno, y luego no me deja auditar aunque reasigne los turnos, cambia su estado a Pendiente de Auditoria sin poder auditarla. Es necesario que este estado cambie a auditada para poder ver los reportes C2

### Resultado esperado 
* Poder auditar agendas con pacientes suspendidos

### Pasos para reproducir el problema 
1. suspender un paciente de una agenda con varios turnos
2. Notar que no es posible auditarla ...
3. 

![image](https://user-images.githubusercontent.com/39344609/62231128-c354e600-b399-11e9-84ab-8968a5d5c73d.png)
![image](https://user-images.githubusercontent.com/39344609/62231516-95bc6c80-b39a-11e9-979d-99db1388bcd8.png)

**Comment by palita1991** [comment]
Se arregla en #1381
