### ISSUE TITLE
Citas: Agendas No Nominalizadas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#1392]
### Comportamiento actual
* Cuando se inicia una prestación en una agenda no nominalizada y se cargan pacientes, despues en la HUDS del paciente no se visualiza que asistió a dicha actividad
### Resultado esperado 
* Los pacientes que se cargan en agendas no nominalizadas, es necesario que se visualicen en la HUDS del paciente. 

### Pasos para reproducir el problema 
1. Iniciar prestación en agenda no nominalizada
2. Cargar pacientes
3. visualizar en la Huds de algún paciente que esta prestación nunca se realizó

**Comment by palita1991** [comment]
Se cierra por comentario
https://github.com/andes/api/pull/799#issuecomment-577668874
