### ISSUE TITLE
RUP: Diferencia de altura en badges y botones en relaciones entre conceptos

### ISSUE THREAD

**Issue by JSantarelli** [andes/app#1405]
# Comportamiento actual
* En RUP, las relaciones (badge + botón desvincular) tienen alturas diferentes. No está claro si hay alguna clase modificando el badge y/o el botón o si es un problema heredado de PLEX.

### Resultado esperado 
* Que badges y botones queden nivelados, con la misma altura.

### Pasos para reproducir el problema 
1. Ir al RUP, iniciar una prestación
2. Hacer una relación entre conceptos

![image](https://user-images.githubusercontent.com/5895886/63437686-5addaf80-c401-11e9-9ede-825bd868e32e.png)

**Comment by palita1991** [comment]
Resuelto
![image](https://user-images.githubusercontent.com/30004190/72258089-f5769f00-35eb-11ea-8f1b-23d33fd8c569.png)
