### ISSUE TITLE
HUDS - Hora de una prestación 

### ISSUE THREAD

**Issue by silviroa** [andes/app#1409]
### Comportamiento actual
Cuando se registra y se valida una prestación asociada a una agenda de una fecha anterior a la actual,  la fecha de registro corresponde a la fecha del turno pero los minutos de la hora de la prestación es siempre 08. (por ejemplo, el turno era el 19/08/2019 14.15, se visualiza en la fecha 19/08/2019 14:08)

### Resultado esperado 
Que los minutos del el horario de la prestación corresponda al horario del turno, en el caso de pacientes fuera de agenda, que corresponda al horario indicado al iniciar la prestación

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by palita1991** [comment]
Se cierra ya quedó resuelto en el PR https://github.com/andes/app/pull/1413
