### ISSUE TITLE
CITAS - Fecha de ejecución en el buscador de turnos y prestaciones

### ISSUE THREAD

**Issue by silviroa** [andes/app#1441]
### Comportamiento actual
En el buscador de turnos y prestaciones, para las prestaciones fuera de agenda, en la columna fecha se visualiza la fecha de validación y no la de ejecución.
Lo mismo sucede en el panel lateral cuando se visualiza el detalle de la prestación.

### Resultado esperado 
Que en el campo fecha del listado y en el detalle se visualice la fecha de ejecución de la prestación.

### Pasos para reproducir el problema 
1. Crear desde rup una prestación fuera de agenda del día 01/10/2019
2. Ejecutar y validar la prestación
3. Visualizar el buscador de turnos y prestaciones

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/api/pull/818
