### ISSUE TITLE
HUDS - Visualización de la fecha de ultima evolución de trastornos en el panel lateral 

### ISSUE THREAD

**Issue by silviroa** [andes/app#1442]
### Comportamiento actual
Los trastornos que tienen mas de una evolución se debería visualizar en el panel lateral la fecha de ultima evolución, pero se muestra la fecha de la primer evolución.

### Resultado esperado 
Los trastornos que tienen mas de una evolución visualizar en el panel lateral la fecha de ultima evolución

### Pasos para reproducir el problema 
1. Crear una prestación fuera de agenda, con fecha 01/10/2019
2. Cargar el trastorno diabetes 
3. Validar la prestación 
4. Crear una prestación fuera de agenda (con el mismo paciente que la prestación), con fecha 03/10/2019
5. Cargar el trastorno diabetes
6.  Validar la prestación
7. Visualizar al HUDS del paciente

**Comment by plammel** [comment]
https://proyectos.andes.gob.ar/browse/HUDS-10

**Comment by palita1991** [comment]
Se cierra ya que se soluciona en https://github.com/andes/app/pull/1758 que está mergeado y en producción.
