### ISSUE TITLE
TOP: Bug en nueva solicitud de salida

### ISSUE THREAD

**Issue by kroce** [andes/app#1449]
### Comportamiento actual
* Resumen del problema.
Al crear una nueva solicitud de salida, si se selecciona un tipo de prestación origen (que esté en alguna regla para el efector actual) y luego se elimina dicha prestación se siguen visualizando las posibles organizaciones destino para la prestación seleccionada. 

### Resultado esperado 
* ¿Que espera que suceda?
Que al eliminar la prestación seleccionada, limpie el select de organización destino.
### Pasos para reproducir el problema 
1. Ingresar a la creación de una nueva solicitud de salida
2. Seleccionar un Tipo de Prestación Origen presente en alguna regla del efector (efector, prestación origen)
3. Eliminar la prestación Origen
4. Desplegar el select de Organización Destino.

**Comment by palita1991** [comment]
Se cierra, Resuelto en https://github.com/andes/app/pull/1463
