### ISSUE TITLE
RUP: Conceptos repetidos y con diag principal no excluyente

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1460]
### Comportamiento actual
* Durante la carga de registros en la prestación de Colonoscopia, si se agregan conceptos dentro de la molécula asociada a esa prestación y se guardan los cambios, los conceptos aparecen repetidos en la pantalla de resumen (dentro de la molécula y fuera).
* Además, estos registros repetidos dejan de funcionar como un grupo a la hora de seleccionar el "Procedimiento/diagnóstico principal", no pudiendo validarse la prestación.

### Resultado esperado 
* Que no estén repetidos los conceptos, así no se presta a confusión lo que se está visualizando, y que se pueda seleccionar sólo 1 diagnóstico principal.

### Pasos para reproducir el problema 
1. Iniciar una prestación de Colonoscopia.
2. Arrastrar/agregar conceptos anidados dentro de la molécula principal.
3. Guardar la prestación, el problema sucede en la pantalla de resumen.

![concepto-repetido](https://user-images.githubusercontent.com/11394455/68030594-9c5bc800-fc98-11e9-8f92-0f9032cc5ecc.png)
![diag-principal](https://user-images.githubusercontent.com/11394455/68030602-a087e580-fc98-11e9-9083-3854506342ef.png)

**Comment by liquid36** [comment]
Para resolver el tema de duplicados como mínimo tiene que salir este PR #1384. Par poder detectar efectivamente que es una  molécula con secciones y conceptos adentro.

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1502 https://github.com/andes/api/pull/867
