### ISSUE TITLE
Gestor de usuarios: Error al asignar permisos parciales de gestión de usuarios 

### ISSUE THREAD

**Issue by silviroa** [andes/app#1465]
### Comportamiento actual
Cuando se le habilita a un usuario "A" en una organización solo los permisos de:
- Ver usuarios y permisos
- Modificar permisos
- Ver perfiles
 Y ese usuario "A" quiere dar permisos dentro del organización a otro usuario "B" sale un error 403 y a ese usuario "B" se le borran todos los permisos asignados en la organización.

### Resultado esperado 
Que un usuarios con permisos de: Ver usuarios y permisos, Modificar permisos, Ver perfiles, puedan modificar los permisos de otros usuarios.

### Pasos para reproducir el problema 
1. A un usuario habilitar en el gestor solo permisos para 'Ver usuarios y permisos' y 'agregar|modifcar permisos'
(más todos los permisos necesarios para reproducir el caso, logueo, etc)
2. Ingresar al sistema con el usuario que se modifico
3. Buscar otro usuario que tenga permisos ya cargados
4. No se visualizan dichos permisos
5. Modificar al menos uno de los permisos (cualquiera)
6. Guardar
7. Chequear si aun se visualiza el efector donde se modificaron los permisos de ese otro usuario

**Comment by liquid36** [comment]
Ok, hoy lo veo!

**Comment by liquid36** [comment]
Ajuste un tema de permisos.
