### ISSUE TITLE
HUDS: Los antecedentes cargados (situación) no se visualizan en la HUDS

### ISSUE THREAD

**Issue by kroce** [andes/app#1467]
### Comportamiento actual
* No se visualiza en la HUDS del paciente los antecedentes que tenga cargados.

### Resultado esperado 
* Que si el paciente tiene antecedentes cargados estos se visualicen en la HUDS.

### Pasos para reproducir el problema 
1. Iniciarle una prestación a un paciente
2. Cargarle un antecedente (ejemplo: Antecedente De Caída)
3. Validar la prestación
4. Ingresar a la HUDS del paciente
5. Click en el filtro 
![image](https://user-images.githubusercontent.com/18030170/68765131-d911b280-05fa-11ea-8ea9-ae884f5e179e.png)
6. No se visualiza el antecedente

**Comment by plammel** [comment]
Corregido en https://github.com/andes/app/pull/1504, User Story https://proyectos.andes.gob.ar/browse/HUDS-1
