### ISSUE TITLE
Página principal: Botón de HUDS direcciona a RUP

### ISSUE THREAD

**Issue by plammel** [andes/app#1469]
### Comportamiento actual
Botón de HUDS en pantalla principal redirecciona a RUP
![image](https://user-images.githubusercontent.com/25707055/68855545-33734780-06bd-11ea-808f-acde96467f37.png)

* Resumen del problema.

### Resultado esperado 
* ¿Que espera que suceda?
Que el botón de HUDS direccione a HUDS
### Pasos para reproducir el problema 
1. Página principal --> click en botón de HUDS
![image](https://user-images.githubusercontent.com/25707055/68855618-61588c00-06bd-11ea-89eb-ecb6155db9db.png)

**Comment by palita1991** [comment]
Con los nuevos cambios que se subieron de hud-privacidad, esto sigue siendo un issue @condorpiedra ?

**Comment by palita1991** [comment]
@andrrrl quiero saber tu opinion sobre este issue, para ver si lo dejamos abierto o lo cerramos

**Comment by plammel** [comment]
@palita1991 justo estaba viendo eso ayer con @silviroa . El botón te reenvía a RUP y desde esa pantalla existe un botón que te lleva a la HUDS de paciente. Los accesos y el funcionamiento estarían correcto.
Se cierra.
