### ISSUE TITLE
TOP: Bug al auditar solicitud

### ISSUE THREAD

**Issue by juuliotero** [andes/app#1472]
### Comportamiento actual
* Resumen del problema.
Al auditar un solicitud, si se elige la operación (aceptar/rechazar) muestra un campo para agregar el motivo o indicar la prioridad (PR #1459). Si no se finaliza la carga, y se quiere auditar otra solicitud, sigue mostrando los campos ocultos según la elección anterior.

### Resultado esperado 
* ¿Que espera que suceda?
Que al ir a auditar otra solicitud mientras tengo otra abierta, me oculte los campos de motivo/prioridad.

### Pasos para reproducir el problema 
1. Ir a solicitudes y auditar una
2. Elegir Rechazar/Aceptar y visualizar el campo correspondiente (motivo/prioridad)
3. Hacer clic en el botón auditar sobre otra solicitud del listado

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1619
