### ISSUE TITLE
CITAS - Error al clonar agendas dinámicas con un cupo máximo

### ISSUE THREAD

**Issue by silviroa** [andes/app#1475]
### Comportamiento actual
Actualmente cuando se clona una agenda dinámica planificada con un cupo máximo, si de la agenda original ya se han asignado turnos y ese cupo ha disminuido, al momento de clonar, las nuevas agendas quedan con el cupo que queda disponible en la agenda original y no el total con la fue planificada.

### Resultado esperado 
* Que cuando se clona una agenda dinámica con cupo, las nuevas agendas clonadas tenga el cupo con la que planificada la agenda original. O en su defecto que en el estado de planificación sea posible editar dicho cupo.

### Pasos para reproducir el problema 
1. Crear una agenda dinámica con un cupo máximo de 10 turnos.
2. Publicar la agenda
3. Asignar 2 turnos en la agenda dinamica
4. Clonar la agenda
5. Comprobar el cupo maximo que quedo asignado a la nueva agenda clonada.

**Comment by palita1991** [comment]
Se resuelven en
https://github.com/andes/api/pull/860
https://github.com/andes/api/pull/897
