### ISSUE TITLE
Punto Inicio CITAS: Error al editar carpeta 

### ISSUE THREAD

**Issue by kroce** [andes/app#1488]
### Comportamiento actual
* Editar la carpeta de un paciente y limpiar la actual. En este punto no se puede continuar editando
### Resultado esperado 
* Que se pueda limpiar la carpeta actual de un paciente
### Pasos para reproducir el problema 
1. Ingresar al punto de inicio de citas y seleccionar un paciente con carpeta
2. Moverse a la solapa CARPETAS y hacer click en editar 
3. Limpiar la carpeta

https://www.loom.com/share/3db1883c8584461db8a101ff489376aa

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1618
