### ISSUE TITLE
Punto inicio RUP: No se ocultan agendas dinámicas cuando se filtra por paciente y no hay coincidencia

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1510]
![issue](https://user-images.githubusercontent.com/11394455/70932733-2f6a7a80-2019-11ea-9782-61b5e3d95707.gif)

### Comportamiento actual
* Cuando se filtran agendas **dinámicas** por paciente, desaparecen todos los pacientes que no coincidan con la búsqueda, indicando que la agenda posee 0 pacientes si no coinciden con la búsqueda 

### Resultado esperado 
* Que las agendas que no coincidan con la búsqueda no se muestren, actualmente se muestran como con "0 pacientes".
* Además si no hay coincidencia, no se muestra ningún feedback sobre la situación (no hay ningún "el paciente no se encontró dentro de ninguna agenda") 

### Pasos para reproducir el problema 
1. buscar un paciente que no existe en el filtro
2. las agendas dinámicas que no tienen a ese paciente no se ocultan

**Comment by plammel** [comment]
https://proyectos.andes.gob.ar/browse/RUP-91

**Comment by palita1991** [comment]
Se cierra, ya que se solucionó en https://github.com/andes/app/pull/1717 que ya se encuentra mergeado y en producción
