### ISSUE TITLE
CITAS: Fallo en pantalla "Imprimir carpetas"

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1513]
### Comportamiento actual
* Sólo en algunas agendas (ver screenshots), se genera un error al intentar imprimir las carpetas de pacientes.
* El layout se rompe completamente.
* Se generan errores en la consola del navegador.

### Resultado esperado 
* Que se visualice normalmente la pantalla de impresión de carpetas

### Pasos para reproducir el problema 
1. No está claro, se puede intentar reproducir una agenda como la del screenshot

![error-imprimir-2019-12-17 at 09 22 32](https://user-images.githubusercontent.com/11394455/71103081-3f5c9880-2198-11ea-9ea7-72c673840336.jpg)
![error-imprimir-2019-12-17 at 09 22 311](https://user-images.githubusercontent.com/11394455/71103086-3f5c9880-2198-11ea-97f6-c4ef3b0b6296.jpg)
![error-imprimir-2019-12-17 at 09 22 321](https://user-images.githubusercontent.com/11394455/71103088-3f5c9880-2198-11ea-9c54-d1304fccec79.jpg)
![error-imprimir-2019-12-17 at 09 22 322](https://user-images.githubusercontent.com/11394455/71103090-3ff52f00-2198-11ea-9ef0-eb84b4bd0b75.jpg)
![error-imprimir-2019-12-17-at-09 22 31](https://user-images.githubusercontent.com/11394455/71103092-3ff52f00-2198-11ea-95bb-14efa43078a1.jpg)

**Comment by plammel** [comment]
https://proyectos.andes.gob.ar/browse/RUP-90

**Comment by liquid36** [comment]
https://proyectos.andes.gob.ar/browse/CIT-47

**Comment by liquid36** [comment]
CIT-47
