### ISSUE TITLE
HUDS - Error en la visualización de registros

### ISSUE THREAD

**Issue by silviroa** [andes/app#1519]
### Comportamiento actual
En la visualización de los registros en la HUDS se ve el badge "registro privado" aunque no se trate de un registro privado

### Resultado esperado 
Que el badge "registro privado" solo aparezca en los registros privados

### Pasos para reproducir el problema 
1. Registrar una prestación fuera de agenda
2. Registrar un trastorno y un procedimiento
3. Validar la prestación
4. visualizar los registros en la huds del paciente

![image](https://user-images.githubusercontent.com/11513044/71524357-f39ea300-28ab-11ea-974e-2074b9e12ee4.png)

**Comment by palita1991** [comment]
Se cierra, se soluciona en https://github.com/andes/app/pull/1554
