### ISSUE TITLE
fix(RUP privacidad): cambiar plex-list por plex-radio

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1550]
# Comportamiento actual
* El modal de privacidad, usa plex-list con plex-bool (checkbox) con funcionalidad de radio-button (es decir, un sólo item es seleccionable)
* Ver adjunto:
![image](https://user-images.githubusercontent.com/11394455/73366711-295cf000-428d-11ea-90fc-10e64b2b4caa.png)

### Resultado esperado 
* Que haya radio-buttons en modo vertical (ver demo de PLEX navegando /radio).
* Ver adjunto:
![andes-modal-privacidad-crop](https://user-images.githubusercontent.com/11394455/73367173-ea7b6a00-428d-11ea-8d6e-f691971ada6c.png)

### Pasos para reproducir el problema 
1. Ir a la HUDS, ver el modal de privacidad cuando se selecciona el paciente

**Comment by liquid36** [comment]
resuelto

**Comment by palita1991** [comment]
Resuelto, se cierra issue
