### ISSUE TITLE
CITAS: Revisión de Agendas

### ISSUE THREAD

**Issue by andrrrl** [andes/app#1566]
### Comportamiento actual
* Durante la revisión de una Agenda, hay un plex-select que permite cambiar la prestación (cuando la Agenda tiene más de una prestación configurada); pero cuando se selecciona una de las prestaciones, el plex-select se oculta y ya no se puede cambiar de prestación (por ejemplo si el usuario se equivocó). 

![issue-no-se-puede-cambiar-prestación](https://user-images.githubusercontent.com/11394455/74436638-8dfb7b80-4e45-11ea-8644-3ff8e52ac5a8.gif)

### Resultado esperado 
* Que la prestación se pueda cambiar por otra si se eligió por error. 

### Pasos para reproducir el problema 
1. Seleccionar una agenda con más de 1 prestación configurada, auditable  (publicada, pendiente asistencia, y ya pasó su horario)
2. Seleccionar un turno (agregar paciente si no tiene)
3. Seleccionar una de las prestaciones del plex-select

**Comment by plammel** [comment]
@andrrrl enseñame a hacer esos gifs re pro jajaja

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1641
