### ISSUE TITLE
Ingreso a tablas maestras sin permisos

### ISSUE THREAD

**Issue by kroce** [andes/app#1573]
### Comportamiento actual
* Cuando un usuario no tiene permisos para tablas maestras, de igual manera puede acceder por URL. Luego no puede realizar operaciones pero si visualiza información.

### Resultado esperado 
* Que si el usuario no tiene permisos para tablas maestras no visualice ningún tipo de información.

### Pasos para reproducir el problema 
1. Ingresar con un usuario sin permisos para tablas maestras.
2. Acceder por url a los profesionales
3. Se visualiza el listado de profesionales

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/app/pull/1596 , PR subido dia 23/04/2020
