### ISSUE TITLE
GESTOR DE USUARIOS: No funcionan los switch para seleccionar todos los permisos dentro de un módulo

### ISSUE THREAD

**Issue by juuliotero** [andes/app#1587]
### Comportamiento actual
* Cuando quiero asignar todos los permisos dentro de un módulo, y activo el 'Seleccionar todos', no activa todos los permisos.

![image](https://user-images.githubusercontent.com/7090371/75773985-bc29f800-5d2d-11ea-8bf5-a0e53eefaac5.png)

### Resultado esperado 
* Que al activar el 'Seleccionar todos' me active todos los permisos del módulo

### Pasos para reproducir el problema 
1. Ir al Gestor de Usuarios
2. Seleccionar un profesional
3. Seleccionar una organización para ver/editar los permisos del profesional
4. Ir a Solicitudes, abrir los permisos y activar 'Seleccionar todos'

**Comment by palita1991** [comment]
@juuliotero ese **seleccionar todo** no te activa los tres permisos de abajo ( "Edición de reglas", "mis solicitudes", "anular solicitudes") se refiere a las prestaciones que podes cargar (tenes permiso para todas o solo para algunas en ese caso cargas solo esas) . SI te referías a eso, no seria un issue.

**Comment by juuliotero** [comment]
> @juuliotero ese **seleccionar todo** no te activa los tres permisos de abajo ( "Edición de reglas", "mis solicitudes", "anular solicitudes") se refiere a las prestaciones que podes cargar (tenes permiso para todas o solo para algunas en ese caso cargas solo esas) . SI te referías a eso, no seria un issue.

Habíamos probado y no funcionaba para seleccionar prestaciones. Habría que revisarlo denuevo.

**Comment by plammel** [comment]
> > @juuliotero ese **seleccionar todo** no te activa los tres permisos de abajo ( "Edición de reglas", "mis solicitudes", "anular solicitudes") se refiere a las prestaciones que podes cargar (tenes permiso para todas o solo para algunas en ese caso cargas solo esas) . SI te referías a eso, no seria un issue.
> 
> Habíamos probado y no funcionaba para seleccionar prestaciones. Habría que revisarlo denuevo.

Efectivamente, ese toggle ''Seleccionar todos'' no funciona. Es un issue.

**Comment by plammel** [comment]
https://proyectos.andes.gob.ar/browse/GDU-7

**Comment by plammel** [comment]
> > @juuliotero ese **seleccionar todo** no te activa los tres permisos de abajo ( "Edición de reglas", "mis solicitudes", "anular solicitudes") se refiere a las prestaciones que podes cargar (tenes permiso para todas o solo para algunas en ese caso cargas solo esas) . SI te referías a eso, no seria un issue.
> 
> Habíamos probado y no funcionaba para seleccionar prestaciones. Habría que revisarlo denuevo.

"Seleccionar todos" solo tiene efecto si se selecciona alguna accion (editar, anular, mis solicitudes), caso contrario, no guarda.

**Comment by palita1991** [comment]
Se cierra ya que se resolvió en  https://github.com/andes/app/pull/1740
