### ISSUE TITLE
TOP: cuando el profesional solo tiene permiso para una prestación da error

### ISSUE THREAD

**Issue by juuliotero** [andes/app#1588]
### Comportamiento actual
Si un profesional tiene permisos de solicitudes solo para una prestación, se genera un error al entrar a la pantalla de solicitudes. 
Esto pasa por lo siguiente:

```
if (req.query.tipoPrestaciones) {
            match.$and.push({
                $or: [{ 'solicitud.tipoPrestacion.id': { $in: req.query.tipoPrestaciones.map(e => Types.ObjectId(e)) } },
                { 'solicitud.tipoPrestacionOrigen.id': { $in: req.query.tipoPrestaciones.map(e => Types.ObjectId(e)) } }]
            });
        }

```
Cuando tiene solo un permiso, req.query.tipoPrestaciones no es un arreglo y falla el map.

### Resultado esperado 
Poder filtrar las solicitudes por tipo de prestación aunque tenga permisos para una sola.

### Pasos para reproducir el problema
1. Asignar a un profesional permisos en Solicitudes para una sola prestación
2. Ir a la pantalla de Solicitudes

![image](https://user-images.githubusercontent.com/7090371/75789148-00c28d00-5d48-11ea-8d55-aab61a5e912f.png)

**Comment by palita1991** [comment]
Se resuelve en https://github.com/andes/api/pull/945
