### ISSUE TITLE
DASHBOARD: no descarga CSV

### ISSUE THREAD

**Issue by plammel** [andes/app#1642]
### Comportamiento actual
En el dashboard de CITAS, al hacer click en el botón de descarga de reporte, muestra un mensaje de error y no realiza la descarga. En el dashboard de TOP no se muestran mensajes de error, pero la descarga igualmente no se realiza.

### Resultado esperado 
Que al hacer click en el botón de descarga de reporte, se descargue el archivo.

### Pasos para reproducir el problema 
1. Ir  a ANDES / DASHBOARD / CITAS (/ TOP) 
2. Realizar una búsqueda e intentar descargar un reporte.

![image](https://user-images.githubusercontent.com/25707055/80233668-422b3680-862d-11ea-8b1a-00c8a8a657b2.png)

**Comment by plammel** [comment]
Seguimiento en https://proyectos.andes.gob.ar/browse/MISC-61

**Comment by liquid36** [comment]
https://github.com/andes/app/pull/1708
