### ISSUE TITLE
TOP: Filtra prestaciones sin permiso

### ISSUE THREAD

**Issue by plammel** [andes/app#1665]
### Comportamiento actual
* Resumen del problema.
Al no setear un filtro de prestación destino, la busqueda devuelve algunas solicitudes cuyas prestaciones no encuentran entre las del permiso del usuario
### Resultado esperado 
* ¿Que espera que suceda?
Que al buscar solicitudes sin filtro de prestación destino, la búsqueda solo arroje las que tienen prestaciones permitidas por el usuario.
### Pasos para reproducir el problema 
1. Asignar permiso TOP para una prestación (ej. medicina general)
2. En el buscador de solicitudes buscar por un rango de fechas amplio, que arroje muchos resultados.
3. Verificar en la columna prestación destino de la tabla de resultados, que algunas prestaciones destino no se corresponden con el permiso de usuario

https://github.com/andes/api/blob/8f9aa024c67ac0b47df2775304287db31196033e/modules/rup/routes/prestacion.ts#L299

```
if (req.query.tipoPrestaciones) {
          let tipoPrestaciones = req.query.tipoPrestaciones;
          tipoPrestaciones = Array.isArray(tipoPrestaciones) ? tipoPrestaciones : [tipoPrestaciones];
          match.$and.push({
              $or: [{ 'solicitud.tipoPrestacion.id': { $in: tipoPrestaciones.map(e => Types.ObjectId(e)) } },
              { 'solicitud.tipoPrestacionOrigen.id': { $in: tipoPrestaciones.map(e => Types.ObjectId(e)) } }]
          });
      }

```

**Comment by plammel** [comment]
https://proyectos.andes.gob.ar/browse/TOP-45

**Comment by sychus** [comment]
![image](https://user-images.githubusercontent.com/19353464/106684323-00a8be00-65a5-11eb-9751-2b5d5df9bbc0.png)

Que onda esto? se puede cerrar?

**Comment by plammel** [comment]
Afirma
