### ISSUE TITLE
Reloj agenda

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#463]
Al crear una agenda el reloj bloquea horarios.
![image](https://user-images.githubusercontent.com/30051357/39711793-2e67ed62-51f7-11e8-9ef4-bbdf002b57bf.png)

**Comment by milagrosn** [comment]
cuando se carga manual no hay problema!

Pendiente para la v3.1.0.

**Comment by NicoDino** [comment]
Planificado para sprint 42

**Comment by jfgabriel** [comment]
Solucionado. Actualizar @andes/plex a versión 3.2.10 o superior
