### ISSUE TITLE
Asignar carpeta de pacientes a través de la dación de turnos

### ISSUE THREAD

**Issue by condorpiedra** [andes/app#484]
Se carga un paciente con documento 26218442 en el Centro de Salud Mariano Moreno.  
Se asigna un turno a través de la operación del turno.  se visualiza el número de carpeta pero no permite confirmar el turno por un error en número de carpeta repetida (problema en el patch de paciente en updateCarpetaEfectores)
https://github.com/andes/api/tree/v3.0.0/core/mpi/routes

**Comment by NicoDino** [comment]
@condorpiedra hola Nati! Esto sucede sin editar el Nro de carpeta?
