### ISSUE TITLE
Clonar agendas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#490]
En la operación de clonar agendas no se visualizan las agendas en conflicto. 
![clonar en conflicto](https://user-images.githubusercontent.com/39344609/40174502-b5e80ed2-59ab-11e8-9ae3-cb035db08c23.PNG)

**Comment by milagrosn** [comment]
Incidente resuelto!!

**Comment by NicoDino** [comment]
Buenisimo! lo cierro entonces
