### ISSUE TITLE
RUP estado no definido (Branch turneroColegio)

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#492]
En el Punto de Inicio de Rup, para el caso de los sobreturnos no es posible llamar al paciente.
Revisar la opción de paciente fuera de agenda
![errorconsolaapp](https://user-images.githubusercontent.com/30051357/40173493-6b4638b6-59a8-11e8-8dfc-f26dc7a04bc6.png)

**Comment by condorpiedra** [comment]
Resuelto  en PR #390
