### ISSUE TITLE
Modulo solicitudes - Operaciones

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#493]
No funcionan las operaciones en el modulo solicitudes

**Comment by Silvinagabriela** [comment]
![operacionessolicitudes](https://user-images.githubusercontent.com/38788179/40366681-253feac4-5dae-11e8-934f-8ef76f801394.PNG)

**Comment by milagrosn** [comment]
Pendiente para la v3.1.0

**Comment by NicoDino** [comment]
Planificado en sprint 42, actualización completa del módulo solicitudes
