### ISSUE TITLE
MPI-campo localidad

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#494]
En MPI (datos de domicilio de un paciente): el campo localidad no trae los datos cuando selecciono una provincia (ni al hacer click para que me muestre todas ni tipeando la localidad)
En la consola trae el arreglo vacío. 
![campolocalidad](https://user-images.githubusercontent.com/30051357/40236246-457fa88e-5a83-11e8-82fc-6ffad6246dd1.png)

**Comment by sychus** [comment]
Esto se debe a que no todas están cargadas en la BD. Sólo las de Neuquén. Igual lo dejo abierto ya que es algo que deberíamos completar.

**Comment by milagrosn** [comment]
Aparecen localidades de Neuquén, pero no de otras provincias.

Pendiente para v3.1.0
