### ISSUE TITLE
RUP Screening de otoemisión acustica neonatal (procedimiento)

### ISSUE THREAD

**Issue by negro89** [andes/app#500]
Se permite guardar la consulta sin completar ningún campo como requerido. Luego se produce un error.
![otoemision acustica](https://user-images.githubusercontent.com/37875706/40383258-ce01e400-5dd6-11e8-9a77-b3004572d808.png)

**Comment by milagrosn** [comment]
![evaluacion_antecedentes_oto](https://user-images.githubusercontent.com/39344609/40614935-249cc2e8-625b-11e8-8070-856fd1172798.PNG)
También permite validar prestación con el 1er campo cargado (Evaluacion de antecedentes), y me sigue figurando una prestación que quedó eliminada!

**Comment by NahirSaddiRTO** [comment]
Todo Ok!! No me permitió guardar sin antes completar todos los datos requeridos (Evaluación De Antecedentes, Otoemisión Acústica De Oído Izquierdo, Otoemisión Acústica De Oído Derecho)
:+1:
