### ISSUE TITLE
Operaciones de turno - turnos reservados

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#506]
No se visualizan los turnos pendientes cuando son turnos reservados y la agenda tiene estado disponible (Llave - Profesional).

Dar turnos en una agenda con turnos reservados y en estado disponible - ir a punto de inicio - buscar pacientes - hacer clic en operaciones del turno - 

(testing/demo/producción)

**Comment by NicoDino** [comment]
Analizando el issue con @condorpiedra nos dimos cuenta que esto se pensó inicialmente para que funcione de esta manera, no sería un BUG.

Queda pendiente analizar la mejora propuesta y en caso de hacer el cambio sale en el próximo release.

**Comment by milagrosn** [comment]
Pendiente para la v3.1.0

**Comment by NicoDino** [comment]
fixed en PR #575
