### ISSUE TITLE
PrestamosHC - historial de prestamos

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#509]
No se visualiza el movimiento - prestación o servicio a la que fue prestada.
Para poder buscar una carpeta en particular es necesario poder ver  donde esta ubicada físicamente. 

![1](https://user-images.githubusercontent.com/38788179/40625627-0457d2b4-628a-11e8-8fc0-378db33085e3.PNG)

**Comment by milagrosn** [comment]
Pendiente para v3.1.0

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551
