### ISSUE TITLE
Integración ANDES-SIPS

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#522]
un horario suspendido en ANDES, se muestra como turno dado y repetido en SIPS - Toma los datos de un sobreturno dado en el mismo horario. 
![paciente1](https://user-images.githubusercontent.com/38788179/40974299-80bf6880-689d-11e8-9ee6-8d16f9f69bce.PNG)
![paciente2](https://user-images.githubusercontent.com/38788179/40974567-569bebfe-689e-11e8-868b-be6482100b4f.PNG)

**Comment by condorpiedra** [comment]
Esta es la forma en que se visualiza en Sips.  Es correcto la forma en que se muestra porque en el mismo horario se suspendió un turno y asignó un sobreturno
