### ISSUE TITLE
Prestación mal cargada en mensaje de texto

### ISSUE THREAD

**Issue by milagrosn** [andes/app#523]
Corregir prestación en mensaje de texto.
![mensaje de texto](https://user-images.githubusercontent.com/39344609/40986513-c21a3098-68bc-11e8-8645-63f5d59510bb.PNG)

**Comment by milagrosn** [comment]
![mensaje_texto](https://user-images.githubusercontent.com/39344609/41170794-4af3b308-6b24-11e8-80d7-eb2e738bdef1.PNG)

**Comment by milagrosn** [comment]
Pendiente para v3.1.0

**Comment by milagrosn** [comment]
![undefined](https://user-images.githubusercontent.com/39344609/41309516-59ae4dca-6e55-11e8-955d-7a83b49c33e4.PNG)

**Comment by milagrosn** [comment]
este ultimo mensaje se envía ahora para turno "consulta de oftalmología".

**Comment by Silvinagabriela** [comment]
![whatsapp image 2018-06-29 at 13 18 19](https://user-images.githubusercontent.com/38788179/42103500-ac28637c-7b9f-11e8-9b8f-1b2abe6aa436.jpeg)
