### ISSUE TITLE
Prestamos HC - prestar

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#525]
Al prestar una carpeta solicita un dato requerido, que no permite ingresar, por lo cual no se puede completar la operación.
![prestamoshc](https://user-images.githubusercontent.com/38788179/40991154-3fc2b8e2-68c9-11e8-8653-89f6a9318ab3.PNG)

**Comment by milagrosn** [comment]
Pendiente para v3.1.0

**Comment by matiurrutia** [comment]
Esto sucedía cuando había un error en la función "prestar carpeta" (ya se soluciono este error) y no dejaba avanzar con el préstamo de la carpeta.
El destino y el responsable son datos que se cargan automáticamente desde el turno, y si la solicitud de carpeta es manual se completan estos datos en el formulario de solicitud manual después de seleccionar un paciente.
Si los requerimientos cambiaron avisenme y cambio la regla.

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551

**Comment by milagrosn** [comment]
Corregido!!!!!
