### ISSUE TITLE
MPI - ReNaPer

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#527]
Mejora: 
Caso: Ingresar un DNI cambiando un dígito - validar con ReNaPer - Muestra la validación correcta - intentar corregir el dígito que se cambio al principio. - (si se cancela la operación te saca de pantalla).
Incluir la posibilidad de corregir el dato si la validación no es la deseada.

**Comment by NicoDino** [comment]
Cierro Issue - Funcionalidad solicitada mergeada desde PR #533
