### ISSUE TITLE
PrestamosHC

### ISSUE THREAD

**Issue by milagrosn** [andes/app#531]
se pueden realizar prestamos manuales (desde botón +) pero al asignarle otro profesional no lo reconoce en el préstamo y le asigna la carpeta al profesional q figura la carga automática.

**Comment by matiurrutia** [comment]
Cuando se quiere asignar otro profesional? antes o despues de realizar el prestamo manual?

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551

**Comment by milagrosn** [comment]
Corregido!!
