### ISSUE TITLE
Editar agenda - Espacios físicos

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#540]
Al editar una agenda publicada o disponible, en espacios físicos, muestra por un lado los espacios del efector y por el otro los espacios de todos los efectores. 
Sugiero que con un solo campo de búsqueda se pueda elegir los espacios del efector y se visualicen en el mapa.
![espaciofisico](https://user-images.githubusercontent.com/38788179/41364805-1a2da8da-6f0e-11e8-971e-c4caf7aed077.PNG)

**Comment by milagrosn** [comment]
Resuelto!
