### ISSUE TITLE
Editar agenda -  equipamiento en espacio fisico

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#541]
No permite buscar espacios físicos por equipamiento. 
![espacio fisico](https://user-images.githubusercontent.com/38788179/41365812-caecc190-6f10-11e8-92b7-177daa7be6af.PNG)

**Comment by cesarlinux** [comment]
![image](https://user-images.githubusercontent.com/755746/57229770-44941b00-6fed-11e9-85f7-bd63392f6ca7.png)
No existe el input para equipamiento
