### ISSUE TITLE
Editar agenda - agregar profesional

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#544]
*En producción
Al editar una agenda y agregarle el profesional se cargan todos los profesionales existentes en la tabla. 
PASOS PARA REPRODUCIR EL ERROR: 
-Tomar una agenda cualquiera  
-Hacer clic en editar 
-agregar profesional.
- empezar a escribir el nombre en el combo para que despliegue el listado de profesionales.
- guardar (con el combo desplegado) 
![profesionales](https://user-images.githubusercontent.com/38788179/41368669-fe9d57fe-6f18-11e8-8a41-293dbe5bbccc.png)

Resultado: Se cargan todos los profesionales existentes.

**Comment by NicoDino** [comment]
Listo para testing

**Comment by negro89** [comment]
El error persiste para el siguiente caso:
- Ingresar a la pantalla de edición
- En el campo "profesional" comenzar a escribir para que se despliegue el listado de posibles profesionales
- Guardar sin haber agregado ni quitado profesionales

Por el contrario si habiendo ingresado a la pantalla de edición se agrega o quita un profesional ya no se reproduce el error.

**Comment by milagrosn** [comment]
Corregido!!!!
