### ISSUE TITLE
PrestamosHC - Prestamos de Carpetas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#552]
Check "prestar carpetas": Permite prestar la misma carpeta a dos lugares distintos.
![prestamos](https://user-images.githubusercontent.com/38788179/41481921-3682480e-70aa-11e8-9399-e13bd572d4aa.PNG)

**Comment by matiurrutia** [comment]
Si la solicitud de carpeta es MANUAL(como se ve en la captura), no permite prestar, el botón se visualiza como PRESTADA y ademas esta deshabilitado. Cuando efectivamente esta habilitado el botón PRESTAR, al darle click automáticamente desaparece la solicitud manual.
Si la solicitud de carpeta es AUTOMÁTICA, SIEMPRE se visualizara en el listado (este o no este prestada la carpeta).
Si la carpeta esta prestada, no importa si es automática o manual, nunca va a permitir que se preste a dos lugares diferentes. La manera de ver que la carpeta este prestada en dos lugares es en la solapa PRESTAMOS DE CARPETAS. Ya que en la solapa de PRESTAMOS DE CARPETAS siempre se visualizaran las SOLICITUDES, sea cual sea el estado que tengan las carpetas.
**Verificar de nuevo esta issue**

**Comment by Silvinagabriela** [comment]
Permite prestar la misma carpeta en solicitudes automáticas. 
![prestamos](https://user-images.githubusercontent.com/38788179/41612070-29845874-73c8-11e8-8d7e-8e55e9c82177.PNG)

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551
