### ISSUE TITLE
PrestamosHC - Imprimir

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#554]
Al hacer clic en el botón imprimir no permite continuar 
![imprimirhc](https://user-images.githubusercontent.com/38788179/41482646-a3a9b302-70ac-11e8-8025-486ea3ed5f93.PNG)

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551

**Comment by milagrosn** [comment]
Corregido!!
