### ISSUE TITLE
PrestamosHC - Actualización de pantallas. 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#555]
No se **actualizan** las pantallas automáticamente, es necesario refrescar para poder ver los cambios o movimientos de carpetas cuando se navega entre solapa y solapa. 
En el caso de "historial de prestamos" deja guardadas las ultimas búsquedas. No se actualiza al cambiar de solapa. 
Esto también sucede en "prestamos de carpetas" -> "Devolver" ->campo "observaciones". 
Ingresar texto - guardar - repetir operación - Resultado: Muestra el mismo texto que se ingreso en la operación anterior.

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551
