### ISSUE TITLE
PrestamosHC - Agregar solicitud manual

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#556]
Corregir el nombre del botón para volver a la solapa de solicitudes. 
![boton](https://user-images.githubusercontent.com/38788179/41483410-68ce94ac-70af-11e8-8b3a-e086a86f2454.PNG)
![boton2](https://user-images.githubusercontent.com/38788179/41483414-6991cf62-70af-11e8-9544-c1c152d0fffb.PNG)

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551

**Comment by milagrosn** [comment]
Se cambio nombre, ok!!!!
