### ISSUE TITLE
PrestamosHC - Ubicación 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#557]
Prestamos de carpeta > ubicación > No muestra la ubicación de la carpeta
![espacio fisico](https://user-images.githubusercontent.com/38788179/41483724-a814d9f4-70b0-11e8-9662-8a16ac634a70.PNG)

**Comment by matiurrutia** [comment]
https://github.com/andes/app/pull/551

**Comment by milagrosn** [comment]
Corregido!!!!
