### ISSUE TITLE
Login: UI no responsive

### ISSUE THREAD

**Issue by jfgabriel** [andes/app#558]
La UI de Login no es responsive.
Se sugiere ocultar los margenes, y los logo de OneLogin y RedTICS cuando se muestre en una pantalla pequeña

![image](https://user-images.githubusercontent.com/16528734/41513326-7880b3cc-7270-11e8-8b88-16d05dd211a7.png)

**Comment by JSantarelli** [comment]
#589

**Comment by sychus** [comment]
muy bueno @JSantarelli :1st_place_medal:
