### ISSUE TITLE
RUP - Error en visualización de planes

### ISSUE THREAD

**Issue by silviroa** [andes/app#570]
### Comportamiento actual
Cuando se registra un plan sin seleccionar organización y/o profesional destino, no es posible visualizar la prestación completa, ni al validar ni al acceder desde la HUDS del paciente.

### Resultado esperado
Visualizar una prestación con planes que no tengan asignado organización y/o profesional destino.

### Pasos para reproducir el problema. 
1. Iniciar una prestación
2. Registrar un plan y no seleccionar organización y profesional destino
3. Guardar la prestación

![image](https://user-images.githubusercontent.com/11513044/41791990-d28c1b16-762d-11e8-9921-c498fac1898b.png)

**Comment by condorpiedra** [comment]
Resuelto
