### ISSUE TITLE
RUP - Procedimientos repetidos en resultados del buscador

### ISSUE THREAD

**Issue by silviroa** [andes/app#571]
### Comportamiento actual
Cuando se busca un concepto en el buscador, en caso de retornar conceptos cuyo semantic tag sea procedimiento o regimen-Tratamiento, estos se ven duplicados. 

### Resultado esperado. 
Cuando se busca un procedimiento debería visualizarse una vez como procedimiento y una vez como plan (procedimiento a futuro).

### Pasos para reproducir el problema. 
1. Iniciar una prestación (ir a ejecutar la prestación)
2. Seleccionar el buscador básico
3. Buscar un procedimiento

![image](https://user-images.githubusercontent.com/11513044/41825280-fda0f796-77f3-11e8-825b-b86f220532de.png)

**Comment by fersastre** [comment]
En revisión y fix del bug.
