### ISSUE TITLE
RUP - Indicar primera vez para C2

### ISSUE THREAD

**Issue by silviroa** [andes/app#576]
### Comportamiento actual
Cuando un concepto snomed registrado en una prestación se mapea a un CIE10 que es C2 se debe indicar en la validación si se trata de un registro de primera vez o ulterior. Actualmente se registra usando un slide, el que por defecto guarda un valor "false".

### Resultado esperado 
Cuando se tenga un concepto que es C2, indicar primera vez con un conjunto de opción "SI" o "NO", que no tenga ningún valor asociado por defecto y al momento de validar chequear que se haya seleccionado algún valor. En caso de no haber registrado el valor mostrar un cartel tipo popUp que diga: _"En la consulta se han registrado conceptos que son C2, por favor indique si se trata de una consulta de primera vez o no"._

### Pasos para reproducir el problema 
1. Ejecutar una prestación
2. Registrar el concepto "varicela"
3. Guardar la prestación

![image 2](https://user-images.githubusercontent.com/11513044/41858196-a2516886-786f-11e8-9ee3-73f534665925.png)

**Comment by matiurrutia** [comment]
Es necesario cambiar el slide de selección "indicar primera vez" por SI o NO? o solo agregar la validación de que si hay un C2, sin seleccionar como primera vez, muestre el popUp?

**Comment by silviroa** [comment]
Si... hay que cambiar el slide por radios con SI / NO. No tiene que haber un valor por defecto, debe ser un dato que si o si cargue el profesional.
