### ISSUE TITLE
RUP - Odonto: no se cargan los planes sobre el odontograma

### ISSUE THREAD

**Issue by silviroa** [andes/app#586]
### Comportamiento actual
Cuando se carga un plan asociado a una cara o a una pieza dental completa se registra como procedimiento intraconsultorio y no como plan.

### Resultado esperado 
Cuando se carga un plan asociado a una cara o a una pieza dental completa se pueda visualizar en el odontograma como un plan.

### Pasos para reproducir el problema 
1. Iniciar prestación "Consulta de odontología"
2. Seleccionar una cara sobre una pieza dental 
3. Buscar el procedimiento Tratamiento de conducto
4. Aplicar el filtro de Planes
5. Agregar el concepto a la consulta

![image](https://user-images.githubusercontent.com/11513044/42095440-fe890412-7b88-11e8-9a18-de6ac9a41e61.png)

**Comment by Silvinagabriela** [comment]
Continua el error
