### ISSUE TITLE
RUP - Odonto: Selección de más de una cara de una pieza dental

### ISSUE THREAD

**Issue by silviroa** [andes/app#587]
### Comportamiento actual
Al intentar cargar un concepto asociado al odontograma solo permite seleccionar una cara o la pieza dental completa

### Resultado esperado 
Se debe poder cargar un procedimiento y asociarlo a mas de una cara (Por ejemplo, es posible indicar una restauración con amalgama sobre dos caras de un diente)

### Pasos para reproducir el problema 
1. Iniciar una prestación "Consulta de odontología"
2. Sobre el odontograma seleccionar una cara y luego intentar seleccionar otra mas

**Comment by andrrrl** [comment]
Está listo y subido a la misma rama
