### ISSUE TITLE
RUP-piezas pintadas no vinculadas

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#591]
### Comportamiento actual
* Al ejecutar una prestación de CONSULTA DE ODONTOLOGÍA quedan pintadas piezas que no fueron vinculadas a ningún concepto.

### Resultado esperado 
* Al ejecutar una prestación de CONSULTA DE ODONTOLOGÍA se pinten solo las piezas dentales vinculadas a conceptos seleccionados

### Pasos para reproducir el problema 
1. Ejecutar una prestación CONSULTA DE ODONTOLOGÍA 
2. Seleccionar piezas dentales del odontograma (No asignarle ningun concepto)
3. Guardar la prestación

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->
![piezas pintadas no vinculadas](https://user-images.githubusercontent.com/30051357/42106474-8b1663d6-7baa-11e8-9fb2-a5e6ff5adf6e.png)

**Comment by andrrrl** [comment]
Ahh está clarísimo.
