### ISSUE TITLE
RUP- conceptos no correspondientes a odontología vinculados a piezas dentales

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#592]
### Comportamiento actual
* Al ejecutar una prestación de CONSULTA DE ODONTOLOGÍA se vinculan conceptos que no son de odontología vinculados a piezas dentales

### Resultado esperado 
* Al ejecutar una prestación de CONSULTA DE ODONTOLOGÍA se vinculen únicamente conceptos de la prestación a las piezas dentales

### Pasos para reproducir el problema 
1. Ejecuta una prestación CONSULTA DE ODONTOLOGÍA
2. Buscar el concepto fiebre
3. Seleccionar una pieza dental
4. Vincular el registro fiebre a la pieza dental

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->
![concepto vinculado a pieza dental](https://user-images.githubusercontent.com/30051357/42107225-ec9a39a0-7bac-11e8-838f-b5a0c47cb95d.png)

**Comment by andrrrl** [comment]
Ya está listo para testear esto @NahirSaddiRTO :relaxed:

**Comment by andrrrl** [comment]
hay que hacer `npm i` para que instale la última versión de Plex :thinking:
