### ISSUE TITLE
ESPACIOS FÍSICOS - Nuevo Espacio Físico.

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#594]
Agregar nuevo espacio físico al efector.

### Comportamiento actual
Al hacer clic en el botón nuevo espacio físico la pantalla queda en blanco

### Resultado esperado 
* Completar los datos necesarios para poder agregar un nuevo espacio físico. 

### Pasos para reproducir el problema 
ingresar a tm/espacio_fisico
hacer clic en nuevo espacio físico.

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by Silvinagabriela** [comment]
![sin titulo](https://user-images.githubusercontent.com/38788179/42174511-0131edec-7df9-11e8-9481-8dea69d18a7f.png)

**Comment by Silvinagabriela** [comment]
![1](https://user-images.githubusercontent.com/38788179/42174688-939f9904-7df9-11e8-80ad-e97b38cac709.PNG)

**Comment by milagrosn** [comment]
corregido!!!

**Comment by milagrosn** [comment]
habilitar permisos de "Tablas Maestras" para poder tener acceso.
