### ISSUE TITLE
Eliminar la referencia del turno en la solicitud 

### ISSUE THREAD

**Issue by NahirSaddiRTO** [andes/app#596]
### Comportamiento actual
* Cuando a partir de una solicitud doy un turno y luego lo libero o lo suspendo, no se elimina la referencia del turno por lo que dicha solicitud se pierde.

### Resultado esperado 
* Cuando a partir de una solicitud doy un turno y luego lo libero o lo suspendo, se debería eliminar la referencia al turno para que la solicitud quede disponible para usarse en otro momento.

### Pasos para reproducir el problema 
1. Seleccionar un paciente desde punto de inicio
2. Darle un turno a partir de una solicitud creada
3. Desde el gestor de agendas visualizar la agenda con el turno dado al paciente seleccionado y suspender o liberar el turno

![image](https://user-images.githubusercontent.com/30051357/42278395-0e1c9c0e-7f71-11e8-93ec-eb0e710aaaa4.png)
![image](https://user-images.githubusercontent.com/30051357/42278429-2bec23a8-7f71-11e8-8f76-16eab2955f4f.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
Resuelto en pull request 365.
