### ISSUE TITLE
SOBRETURNO. Botón de turno doble

### ISSUE THREAD

**Issue by milagrosn** [andes/app#597]
### Comportamiento actual
* Al dar un sobreturno y querer asignarle turno doble el botón no responde.

### Resultado esperado 
* El botón "turno doble" debería responder al querer asignarselo al sobreturno.

### Pasos para reproducir el problema 
1. Dar un sobreturno
2. A este sobreturno darle turno doble
3. No responde el botón de "turno doble"

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by NicoDino** [comment]
Planificado sprint 42.

**Comment by liquid36** [comment]
@NicoDino ¿Qué paso con esto?

**Comment by NicoDino** [comment]
Está pendiente, en el próximo pr en citas lo agregamos!

**Comment by condorpiedra** [comment]
Analizar si es necesario ocultar esta opción para los sobreturnos

**Comment by sychus** [comment]
Esto es un engendro... lo cerramos y no se hace.
