### ISSUE TITLE
CITAS. Sobreturno - Nro. de carpeta

### ISSUE THREAD

**Issue by milagrosn** [andes/app#599]
### Comportamiento actual
* En un sobreturno dado no permite editar el nro. de carpeta

### Resultado esperado 
* Poder editar número de carpeta de los sobreturnos.

### Pasos para reproducir el problema 
1. Agregar un sobreturno a una agenda,
2. Posicionados sobre el paciente del sobreturno editar/cargar desde el botón "Editar Carpeta" un número
3. Guardar
4. No se puede ver el número recién habilitado.

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by NicoDino** [comment]
Planificado sprint 42

**Comment by milagrosn** [comment]
Resolver en branch v3.4.0
