### ISSUE TITLE
Cambiar label del botón de paciente fuera de agenda a paciente no planificado

### ISSUE THREAD

**Issue by silviroa** [andes/app#602]
### Comportamiento actual
En el punto de inicio de RUP el botón para registrar una nueva prestación dice "Paciente fuera de agenda" 

### Resultado esperado 
En el punto de inicio de RUP el botón para registrar una nueva prestación debería decir "Paciente no planificado" 

### Pasos para reproducir el problema 
1. Ingresar al punto de inicio de RUP

![image](https://user-images.githubusercontent.com/11513044/42341677-40ab8a32-806a-11e8-82f2-81138ec9bcd8.png)

**Comment by palita1991** [comment]
Se cierra, no es más un requerimiento.
