### ISSUE TITLE
Sugerencias UI CITAS

### ISSUE THREAD

**Issue by NicoDino** [andes/app#615]
* En el gestor de agendas, “Citación por segmento” debería ir debajo del nombre del bloque, con estilo “small” y “muted” 

![image](https://user-images.githubusercontent.com/8285880/42586997-d7553998-850f-11e8-8831-c86bca2a5348.png)

* En caso de que el bloque no tenga nombre mostrar “Bloque n° X”

* Menos margen en los turnos disponibles totales
![image](https://user-images.githubusercontent.com/8285880/42587073-07fe5aa2-8510-11e8-9254-a71c4d580f30.png)

* Dejar en color sólo las operaciones más importantes. El resto agruparlas en un dropdown
![image](https://user-images.githubusercontent.com/8285880/42587099-1b35aabc-8510-11e8-9aeb-e2cfa35e5d51.png)

* Ubicación del botón de enviar mensaje debería ir a la derecha
![image](https://user-images.githubusercontent.com/8285880/42587125-2cc03c3e-8510-11e8-9f85-ae4bbb0e08a3.png)

* Los botones no deben tener íconos
![image](https://user-images.githubusercontent.com/8285880/42587270-87a93d6c-8510-11e8-944d-a9d42fffe5c1.png)

* El header de agenda de “Agregar nota” debería tener un estilo similar al de la agenda
![image](https://user-images.githubusercontent.com/8285880/42587316-b2e39914-8510-11e8-8b57-0c15c88afa14.png)

* El tooltip no se ve:
![image](https://user-images.githubusercontent.com/8285880/42587344-ca0bdc3c-8510-11e8-8e63-6e7396777186.png)

* En Reasignación manual de turnos  usar un header similar al de la agenda (ver punto anterior)
![image](https://user-images.githubusercontent.com/8285880/42587358-d7b0e936-8510-11e8-9c90-25264134832e.png)

* “Envío de SMS”: utilizar el label de plex-bool. No usar los badges

* Una agenda suspendida sin turnos no debería habilitar el botón “Reasignar”
![image](https://user-images.githubusercontent.com/8285880/42587382-ed03977a-8510-11e8-8a7f-248bd04ba802.png)

* Suspender agenda: Usar la propiedad “required” y NO utilizar una alerta:

* Cuando entro a la opción “Suspender” y cancelo me queda el panel abierto:

**Comment by cesarlinux** [comment]
Se debe proponer como mejora con US
