### ISSUE TITLE
Arancelamiento. Sobreturnos

### ISSUE THREAD

**Issue by milagrosn** [andes/app#619]
### Comportamiento actual
* El botón arancelamiento no aparece para los sobreturnos dados.

### Resultado esperado 
* Poder ver el botón Arancelamiento en los sobreturnos
### Pasos para reproducir el problema 
1. Dar un sobreturno
2. Buscarlo desde "Citas.Punto de inicio", no se muestra habilitado el botón de Arancelamiento
3. 

<!-- Código relevante 
![image](https://user-images.githubusercontent.com/39344609/42591540-5d532976-851d-11e8-9dde-f0f034cb5a93.png)

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by NicoDino** [comment]
Solucionado en PR #575
