### ISSUE TITLE
MPI: Búsqueda con nombre parcial

### ISSUE THREAD

**Issue by jfgabriel** [andes/app#627]
### Comportamiento actual
* Cuando se busca un paciente con una parte del nombre el resultado no aparece

### Resultado esperado 
* ¿Que espera que suceda?
Si busco "MANUEL SAN" debería listar, por ejemplo, "MANUAL SANGUESA" como resultado
![image](https://user-images.githubusercontent.com/16528734/42762122-d0d86d72-88e5-11e8-8d71-2a27becce8a0.png)

### Pasos para reproducir el problema 
1. Entrar a demo
2. Entrar a MPI
3. Buscar manuel san
4. En los resultados NO aparece MANUEL SANGUESA
![image](https://user-images.githubusercontent.com/16528734/42762100-c78a06ae-88e5-11e8-93aa-0eca412c869b.png)

**Comment by NicoDino** [comment]
Agregado en nueva versión api MPI por team core. Cierro issue
