### ISSUE TITLE
CITAS - Punto de Inicio -Error al dar un turno

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#639]
**Este error se repite en producción**

### Comportamiento actual
* Solicita cargar un paciente cuando en realidad ya se seleccionó - esto lo hace en el panel/calendario

### Resultado esperado 
* No debería solicitarlo ya que el paciente se seleccionó anteriormente 

### Pasos para reproducir el problema 
1. seleccionar un paciente 
2. Dar un turno (hacerlo con una conexión a Internet débil) 
3. Permite continuar, se visualiza el calendario
4. Al seleccionar la agenda solicita seleccionar un paciente

![1](https://user-images.githubusercontent.com/38788179/42897926-01087880-8a98-11e8-8b12-bd50948c7c6c.PNG)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
@Silvinagabriela esto sigue vigente?

**Comment by Silvinagabriela** [comment]
@kroce no ha pasado últimamente. Lo cerramos, si sucede de nuevo lo abrimos.
