### ISSUE TITLE
CITAS - Turnos - Ultimas búsquedas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#640]
### Comportamiento actual
Para buscar agendas en el calendario desde las ultimas búsquedas hay que hacer doble clic sobre la agenda que se desea seleccionar
### Resultado esperado 
Hacer solo un clic para visualizar las agendas. Ya que para ninguna función del sistema es necesario hacer doble clic, tener que hacerlo en esta parte se presta a confusión, da a entender que no se encontraron agendas. 

### Pasos para reproducir el problema 
1. dar un turno a un paciente
2. filtrar agendas desde las ultimas búsquedas 
3. hacer doble clic para visualizar las agendas

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
Fixed!
