### ISSUE TITLE
RUP - Colapsar registros

### ISSUE THREAD

**Issue by silviroa** [andes/app#644]
### Comportamiento actual
Cuando en prestación carga por defecto el elemento de registro informe de la consulta para la evolución general, el resto de los elementos que se agregan a la consulta se ven desplegados y eso puede resultar confuso al profesional.

### Resultado esperado 
Para las prestaciones que cargan por defecto el elemento de registro informe de la consulta para la evolución general, el resto de los elementos que se agreguen a la consulta debe verse colapsados por defecto

### Pasos para reproducir el problema 
1. Iniciar una consulta de medicina general
2. Buscar y agregar a la consulta "fiebre" 

![image](https://user-images.githubusercontent.com/11513044/42960099-36b23b3c-8b61-11e8-8f17-00e379d5c084.png)

**Comment by milagrosn** [comment]
Corregido!!
