### ISSUE TITLE
RUP - Cambiar label de motivo de consulta

### ISSUE THREAD

**Issue by silviroa** [andes/app#647]
### Comportamiento actual
Al validar una prestación el profesional debe seleccionar el motivo principal de la consulta y se confunde con lo referido por el paciente.

### Resultado esperado 
Al validar la consulta se debería seleccionar el "procedimiento / diagnostico principal".

### Pasos para reproducir el problema 
1. Iniciar una consulta de clínica medica
2. Agregar evolución al informe
3. Agregar a la consulta fiebre
4. Guardar la prestación

![image](https://user-images.githubusercontent.com/11513044/42960869-82d3b318-8b63-11e8-8514-1690bb8db528.png)

**Comment by milagrosn** [comment]
se modifico label!
