### ISSUE TITLE
CITAS - Reasignar turnos a una agenda clonada con turnos del día.

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#655]
### Comportamiento actual
Solo permite reasignar turnos si la agenda destino tiene turnos programados.

### Resultado esperado 
Se desea reasignar turnos a una agenda con las mismas características que la agenda origen y esta tiene todos turnos del día. - 
Se sugiere que al momento de reasignar turnos el comportamiento sea distinto al de punto de inicio, ya que muchas veces es necesario reasignar turnos a agendas clonadas que contienen la mismas características que la agenda origen.  

### Pasos para reproducir el problema 
1. Crear una agenda con turnos del día, clonarla a otro día y publicarlas 
2. Dar turnos en la original
3. suspender esta y reasignar los turnos a la clonada. (Ej. El profesional no viene y necesito reasignarle los turnos para la próxima agenda)
4.No muestra la agenda como candidata por el tipo de turnos

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
No se hace
