### ISSUE TITLE
Punto de Incio - Dar asistencia

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#660]
### Comportamiento actual
Al querer marcar asistencia desde el punto de inicio aparece un cartel que dice "datos insuficientes"

### Resultado esperado 
Poder marcar la asistencia al paciente

### Pasos para reproducir el problema 
1. dar un turno a un paciente
2. hacer clic en turnos
3. clic en dar asistencia
![sin titulo](https://user-images.githubusercontent.com/38788179/43220129-a3f45488-901f-11e8-91ca-690d87cbb75d.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
corregido!
