### ISSUE TITLE
Punto de inicio - liberar turnos 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#661]
### Comportamiento actual
Falta información

### Resultado esperado 
¿se debe visualizar la información del paciente?

### Pasos para reproducir el problema 
1. dar un turno a un paciente
2. liberar turno
3. 
![captura](https://user-images.githubusercontent.com/38788179/43220490-89e02760-9020-11e8-9289-dac0ca31482a.PNG) 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
Corregido!
