### ISSUE TITLE
CITAS - Punto de Inicio - Editar numero de carpeta

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#663]
### Comportamiento actual
Al hacer clic en botón editar, este desaparece.
### Resultado esperado 
Poder editar el numero de carpeta
![captura](https://user-images.githubusercontent.com/38788179/43279786-69378704-90e5-11e8-93d0-41efd37189e5.PNG)

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by NicoDino** [comment]
Revisé y estaba mal hecho el chequeo de permisos. :fire: :fire: :fire: 
Ya está solucionado y ahora subo el PR :wrench: :wrench: :wrench: 
Aparentemente se dió que no tenés permisos para editar nros de carpeta de paciente, pero el botón se ve igual. El tema es que al picar el botón no muestra la funcionalidad ya que ahí sí estaba chequeando los permisos.

**Comment by NicoDino** [comment]
PR's en app y api con fixes  :point_up: :point_up: :point_up:

**Comment by milagrosn** [comment]
corregido!!
