### ISSUE TITLE
Citas. Nro Carpeta

### ISSUE THREAD

**Issue by milagrosn** [andes/app#665]
### Comportamiento actual
* Cuando desde revisión agrego un turno o sobreturno de algún paciente que no tiene Nro de HC en el efector donde le estoy por dar turno pero si tiene Nro de HC en otro efector, se genera turno con la HC de otro efector.

### Resultado esperado 
* Que el paciente que no tiene nro. de HC no me traiga nro. de HC de otro efector

### Pasos para reproducir el problema 
1. Dar un turno o sobreturno desde Revisión
2. Cargar algún paciente q no tenga HC en el efector donde estoy por dar turno, pero si en otro/s efectores
3. Al verlo desde el gestor se puede ver que trae el nro de HC de otro efector

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by NicoDino** [comment]
Fixeado y mergeado! :call_me_hand:
