### ISSUE TITLE
RUP. Agendas Dinámicas. Agregar pacientes

### ISSUE THREAD

**Issue by milagrosn** [andes/app#685]
### Comportamiento actual
* Al querer agregar paciente desde RUP en una agenda dinámica, desaparece el botón "Agregar paciente" solo permite hasta 3 pacientes cuando el cupo disponible sea mayor.

### Resultado esperado 
* Permitir cargar pacientes al cupo máximo permitido

### Pasos para reproducir el problema 
1. "Agregar paciente"  en una agenda dinámica con un cupo mayor a 3
2.  Agregar dos pacientes mas desde el mismo botón,
3.  Al querer agregar mas pacientes no aparece botón de "Agregar Paciente".

![image](https://user-images.githubusercontent.com/39344609/43856386-bc5a4fdc-9b1e-11e8-85df-27c13279191a.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by Silvinagabriela** [comment]
esperando se resuelva en issus #948 para poder probar..

**Comment by milagrosn** [comment]
Resuelto!!!
