### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by sychus** [andes/app#686]
Pantalla de login

### Comportamiento actual
* Cuando pongo mi usuario y contraseña de login (OneLogin), si el usuario no existe previamente en la colección AuthUsers sale un error que dice que mi usuario y contraseña no es válido.

### Resultado esperado 
* Cuando pongo mi usuario y contraseña de login (OneLogin), debería validar contra el servidor LDAP y si mi usuario no existe o mi contraseña es incorrecta, debe darme el error. Ahora si mis credenciales son correctas debería permitirme ingresar y mostrarme que no tengo permisos para ninguna aplicación de ANDES e insertar el usuario en la colección AuthUsers

### Pasos para reproducir el problema 
1. voy a app.andes.gob.ar
2. Pongo mi usuario y clave (de OneLogin)
3. Si el usuario no existe en la colección y mis credenciales son correctas --> sale el error que mi usuario y contraseña son incorrectos.

**Comment by martinweingart** [comment]
@sychus me parece bien. Con "insertar el usuario en la colección AuthUsers"  te referis a actualizar los datos del usuario?

**Comment by sychus** [comment]
Exacto, si el usuario valida sus credenciales ok, entonces hace un insert en la colección. No le asigna ningún permiso. Simplemente es para que no de un mensaje confuso. Igual no te preocupes lo programo y luego lo vemos juntos.

**Comment by NicoDino** [comment]
@sychus podemos hacer una user con esto y validarla con PO's ???
