### ISSUE TITLE
Búsqueda de profesionales trae más resultados que los esperados

### ISSUE THREAD

**Issue by andrrrl** [andes/app#695]
CITAS / Cualquier lugar donde se busquen profesionales con plex-select

### Comportamiento actual
El buscador trae resultados al escribir un sólo caracter, generando respuestas del servidor muy pesadas y que traen resultados que no tienen que ver con la búsqueda.
Por ejemplo: si se busca al profesional GONZALEZ DARIO ingresando "GONZ DA" se dispara una búsqueda de todos los profesionales con la letra "G", además, cuando se ingresa la parte "DA" suma a la búsqueda todos los apellidos y nombres que contengan "DA", por ejemplo "VIDAL HEIDI"

### Resultado esperado 
* Debería empezar a buscar sólo cuando se ingresan 2 caracteres (o quizás 3), con un timeout (similiar a lo que hace el buscador de SNOMED).
* Debería asegurarse que todo request se cierre automáticamente pasado un tiempo determinado.

### Pasos para reproducir el problema 
1. Ir al módulo CITAS, punto de inicio de Agendas
2. Desplegar los filtros de búsqueda ocultos
3. Buscar profesionales según lo descrito más arriba 

![image](https://user-images.githubusercontent.com/11394455/44036766-fb6bf072-9ee8-11e8-8069-828814b93193.png)

**Comment by liquid36** [comment]
Corrección en parte a este problema: https://github.com/andes/api/pull/393
