### ISSUE TITLE
Citas. Agendas Dinámicas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#696]
### Comportamiento actual
* Al armar una agenda dinámica (fecha y hora cargada) y quiero cambiar el horario no se actualiza la hora en el bloque. Igualmente no tiene ninguna funcion util mostrar la parte de "Bloques" 
### Resultado esperado 
* Que se actualice el bloque cuando hago un cambio en la hora de la agenda

### Pasos para reproducir el problema 
1. Crear una agenda dinamica
2. Antes de "guardar", cambiar horario
3. En el bloque no se ve reflejada la hora actualizada

![image](https://user-images.githubusercontent.com/39344609/44042171-fb2eeb66-9ef5-11e8-93e9-0b0ca3127718.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
Quedó referenciado el PR 729 por error, el que corresponde es el #708

**Comment by milagrosn** [comment]
Corregido!!!
