### ISSUE TITLE
Matriculaciones - Habilitación/Inhabilitan del Profesional

### ISSUE THREAD

**Issue by ghost** [andes/app#702]
### Comportamiento actual
* En la pantalla de edición de datos de un Profesional habilitado, al presionar el Toggle Button q habilita/inhabilita al mismo, se muestra el cuadro de confirmación. En caso de presionar "Cancelar", la acción se cancela pero el Toggle Button pasa a estado "off" de todas formas.
De hecho el Toggle Button cambia de estado incluso antes de Confirmar o cancelar la accion.

### Resultado esperado 
* El Toggle Button debería esperar a la confirmación y/o cancelación de la acción antes de cambiar de estado

### Pasos para reproducir el problema 
1. En el listado de profesionales, seleccionar uno.
2. Presionar el botón "Editar profesional" para pasar a la pantalla de edición de datos.
3. Presionar el Toggle Button
4. Cuando aparezca el cuadro de confirmación presionar "Cancelar"

### Captura
![andes matriculaciones](https://user-images.githubusercontent.com/34943321/44090863-ffbea0a2-9fa1-11e8-9105-474fba30f781.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by condorpiedra** [comment]
Se podría realizar como una mejora, cambiando el componente con el que se implementa la funcionalidad
