### ISSUE TITLE
Matriculaciones - Múltiples solicitudes para un turno 

### ISSUE THREAD

**Issue by ghost** [andes/app#703]
### Comportamiento actual
* Resumen del problema.
Al solicitar un turno, rellenar datos obligatorios y presionar el botón "Confirmar Turno" se descarga un PDF con el detalle del turno y se notifica que el turno fue otorgado correctamente.
Luego, podemos volver a pinchar el botón "Confirmar Turno" muchas veces.

### Resultado esperado 
* ¿Que espera que suceda?
Que solo permita solicitar un turno.

### Pasos para reproducir el problema 
1. Solicitar turno
2. Completar datos obligatorios
3. Confirmar turno
4. Confirmar turno
5. Confirmar turno

![andes matriculaciones](https://user-images.githubusercontent.com/34943321/44094990-0a0b2952-9fae-11e8-8dba-d2ff1e7ddb7a.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
resuelto!!
