### ISSUE TITLE
MPI - Detalle del paciente cuando los datos de contacto no están completos

### ISSUE THREAD

**Issue by silviroa** [andes/app#706]
### Comportamiento actual
Cuando se valida un nuevo paciente desde la app mobile (perfil profesional) al acceder al mismo para darle un turno da un error al intentar mostrar los datos de contacto

### Resultado esperado 
Cuando se valida un nuevo paciente desde la app mobile (perfil profesional) al acceder al mismo para darle un turno mostrar solo los datos registrados.

### Pasos para reproducir el problema 
1. Acceder a la app mobile e ingresar como profesional.
2. Acceder a mpi, escanear a un paciente nuevo y validarlo
3. Ingresar a la app web de andes
4. Acceder al punto de inicio de CITAS
5. Buscar al paciente validado para darle un turno.

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

![image](https://user-images.githubusercontent.com/11513044/44096992-1969a086-9fb3-11e8-8f0b-8c502bd7b9ee.png)

**Comment by NicoDino** [comment]
Solución mergeada con el PR #728.
