### ISSUE TITLE
CITAS > Dar turnos > Búsquedas Recientes

### ISSUE THREAD

**Issue by NicoDino** [andes/app#713]
### Comportamiento actual
* Al picar sobre un profesional dentro de la lista "búsquedas recientes", no se activan los filtros y aparece un error en consola.

### Resultado esperado 
* Luego de picar sobre el profesiona, éste debe aparecer en el select del filtro de profesional

### Pasos para reproducir el problema 
1. Seleccionar paciente > dar turno > picar sobre un profesional en la lista de últimas búsquedas.

![captura de pantalla de 2018-08-15 15-24-43](https://user-images.githubusercontent.com/8285880/44165629-ab5c5780-a09f-11e8-9585-12cc1d56be7b.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
Fixed!
