### ISSUE TITLE
RUP - Cargar prestaciones fuera de agenda con fecha anterior a la de carga

### ISSUE THREAD

**Issue by silviroa** [andes/app#719]
### Comportamiento actual
Cuando se registra una prestación fuera de agenda con una fecha previa a la actual se guarda y se valida la prestación correctamente pero no queda accesible desde el punto de inicio.

### Resultado esperado 
Poder acceder desde el punto de inicio a una prestación fuera de agenda que se registra en una fecha distinta a la actual para ver el resumen o romper la validación.

### Pasos para reproducir el problema 
1. Ingresar al punto de inicio
2. Crear una prestación fuera de agenda
3. Cambiar la fecha y hora de la por defecto
4. Cargar, guardar y validar la prestación
5. Volver al punto de inicio y buscar la prestación en la fecha que fue seleccionada

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
Corregido!!!
