### ISSUE TITLE
CITAS -> Nota en el turno

### ISSUE THREAD

**Issue by kroce** [andes/app#722]
### Comportamiento actual
* Si se asigna un paciente a un turno que tiene una nota, la misma no se visualiza y se pierde en el momento en que se confirma el turno.

### Resultado esperado 
* Al momento de asignar un turno que tiene una nota, se debería poder visualizar / modificar la misma en el momento de la confirmación.

### Pasos para reproducir el problema 
1. Agregar una nota en un turno disponible de alguna agenda.
2. Asignar el turno a un paciente.
3. Visualizar la nota para su posible edición en la confirmación del turno.

**Comment by milagrosn** [comment]
Corregido!!!
