### ISSUE TITLE
CITAS - Numero de HC - Punto de inicio. 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#733]
### Comportamiento actual
Al agregar un numero de HC cuando se da el turno luego no se visualiza en Punto de inicio

### Resultado esperado 
Poder visualizar el numero de HC en el punto de inicio.

### Pasos para reproducir el problema 
1. dar un turno a un paciente cualquiera
2. agregar numero de HC en el turno
3. buscar numero de HC en el punto de inicio. 

![numero de carpeta](https://user-images.githubusercontent.com/38788179/44407360-4a67d000-a534-11e8-8e3e-57534d9236ea.PNG)
![numero de carpeta2](https://user-images.githubusercontent.com/38788179/44407361-4a67d000-a534-11e8-861b-26952f5ba86b.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
Corregido!!
