### ISSUE TITLE
CITAS - Turnos - Descripción de los bloques

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#737]
### Comportamiento actual
Al momento de dar un turno en una agenda de dos bloques muestra la descripción del primer bloque y los turnos del segundo bloque.
### Resultado esperado 
Visualizar la descripción y los turnos disponibles de un mismo bloque

![Uploading Captura1.PNG…]()

### Pasos para reproducir el problema 
1. Partir de una agenda creada con dos bloques, en el primero turnos con llave en el segundo turnos programados
2. dar un turno a un pacinte
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

![captura](https://user-images.githubusercontent.com/38788179/44469840-ba428d00-a5fe-11e8-8242-0ef5d3fc0e9f.PNG)
![captura1](https://user-images.githubusercontent.com/38788179/44469843-ba428d00-a5fe-11e8-8590-db9761717fd9.PNG)

**Comment by kroce** [comment]
Ver si se resuelve con PR #754

**Comment by milagrosn** [comment]
Resuelto!!
