### ISSUE TITLE
CITAS  - Numero de HC 

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#740]
### Comportamiento actual
El numero de HC no se actualiza en turnos ya dados

### Resultado esperado 
El numero de HC se debe actualizar en turnos ya dados
![captura1](https://user-images.githubusercontent.com/38788179/44479071-e1f11f80-a615-11e8-978e-21082300cf2d.PNG)

### Pasos para reproducir el problema 
1. dar un turno a un paciente con numero de HC
2. volver a dar un turno al mismo paciente y corregir el numero de HC
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by kroce** [comment]
Este comportamiento es correcto. Cuando se modifica el número de HC de un paciente sólo se actualizan los números de carpeta en turnos futuros.
