### ISSUE TITLE
CITAS - Arancelamiento - Motivo/diagnostico

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#745]
### Comportamiento actual
Al momento de ingresar una solicitud, se completa el motivo/diagnostico. Luego, cuando se da el turno este campo figura vacío, si se completa, pisa el dato ingresado en la solicitud.

### Resultado esperado 
Al momento de dar el turno visualizar el diagnostico ingresado en la solicitud, y en caso de ser necesario poder corregirlo. 

### Pasos para reproducir el problema 
1. cargar una solicitud a un paciente
2. ingresar el motivo/diagnostico
3. guardar la solicitud
4. dar el turno
5. completar campo diagnostico.
6. chequear este dato en arancelamiento. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by Silvinagabriela** [comment]
Se chequeara luego de la actualización del modulo.

**Comment by kroce** [comment]
@Silvinagabriela podrías verificar si se resolvió este issue así lo cerramos?

**Comment by milagrosn** [comment]
@kroce sigue pasando!

**Comment by milagrosn** [comment]
Corregido!
