### ISSUE TITLE
RUP: Validación de Prestación con conceptos de screening

### ISSUE THREAD

**Issue by condorpiedra** [andes/app#752]
### Comportamiento actual
* En una consulta que no sea de screening de otoemisión se agregan conceptos de "otoemisión acústica"  

### Resultado esperado 
* Cargar datos referidos al screening, guardar y validar la consulta

### Pasos para reproducir el problema 
1. Ingresar a una prestación de un paciente del tipo "Consulta de Audiología General"
2. Agregar los conceptos de "Otoemisión Acústica de Oído Derecho" y "Otoemisión Acústica de Oído Izquierdo"
3. Guardar prestación
4. Intentar validarla

![prestacion](https://user-images.githubusercontent.com/19696043/44674361-a5516980-aa03-11e8-9427-1f41a32de5cd.jpeg)

**Comment by silviroa** [comment]
Resuelto en el PR 771
