### ISSUE TITLE
CITAS - Planilla de consultorio - visualizar obra social

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#761]
### Comportamiento actual
Solicitud de usuarios nivel central - actualmente no se visualiza la edad y la obra social del paciente en la planilla de consultorio. 
### Resultado esperado 
**Incorporar en la planilla de consultorio, edad y obra social.**  (Necesario para poder facturar)

### Pasos para reproducir el problema 
1. Gestor de agendas
2. Seleccionar agenda. 
3. Imprimir planilla de consultorio

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
Se imprime obra social y fecha de nacimiento
