### ISSUE TITLE
CITAS - Gestor de agendas - Detalle de agenda

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#781]
### Resultado esperado 
Visualizar detalle completo de la agenda seleccionada. 
-duración del turno
-prestaciones asociadas *actualmente muestra las prestaciones estén o no asociadas - ver  issus: #780  ( si se trata de mas de un bloque, las asociadas a cada bloque)
-Los tipos de turnos que se clasificaron al momento de crear la agenda. 
-tipo de citación que se selecciono en la agenda y la cantidad de pacientes 

![detalle](https://user-images.githubusercontent.com/38788179/45098592-ae28f600-b0fb-11e8-84e0-2f096e20c0ee.PNG)

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
