### ISSUE TITLE
Editar Organización

### ISSUE THREAD

**Issue by milagrosn** [andes/app#784]
### Comportamiento actual
* Cuando quiero editar datos de una organización no se puede realizar ninguna modificación y aparecen errores en la consola

### Resultado esperado 
* ¿Que espera que suceda?

### Pasos para reproducir el problema 
1. Ingresar "tm/organizacion"
2. Click en botón "Editar" de algún efector
3. cargar datos de edificio, ver error en consola

![image](https://user-images.githubusercontent.com/39344609/45109874-1fc26d80-b117-11e8-939c-64800e853530.png)

**Comment by milagrosn** [comment]
Corregido!!!

**Comment by condorpiedra** [comment]
resuelto
