### ISSUE TITLE
CITAS- Turnos liberados - historial

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#788]
### Comportamiento actual
En turnos reservados, no se visualiza en historial la liberación de los turnos. 

### Resultado esperado 
Visualizar datos del turno liberado.

### Pasos para reproducir el problema 
1. ingresar un turno como autocitación por RUP. 
2. Liberar desde punto de inicio. 
3.

**Comment by kroce** [comment]
Los turnos liberados se muestran en el historial pero una vez que pasó la fecha de la agenda.
