### ISSUE TITLE
RUP - Reemplazar código prohibido por Angular

### ISSUE THREAD

**Issue by jfgabriel** [andes/app#796]
### Comportamiento actual
* En el archivo _ejecucion/prestacionValidacion.component.ts_ hay una manipulación no del DOM que debería reemplazarse por una directiva o similiar

![image](https://user-images.githubusercontent.com/16528734/45259110-86f05400-b39b-11e8-9472-acff0d6b2b8b.png)

**Comment by andrrrl** [comment]
Esa funcionalidad está _deprecated_, ya que los informes de RUP se van a generar desde la API.
