### ISSUE TITLE
CITAS - Clonar Agendas - Horario inicio y fin de la agenda

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#809]
### Comportamiento actual
Se quiere clonar una agenda que tiene hora inicio 13:00hs para el mismo día, en el que ese mismo profesional, tiene una agenda que termina a las 13:00hs. Al coincidir en hora inicio y fin se muestran en conflicto no permitiendo clonar. 
### Resultado esperado 
Poder clonar una agenda que coincide en hora de inicio/fin con otra (agenda 1: de 12 a **13**; Agenda 2: de **13** a 14)

### Pasos para reproducir el problema 
1. crear una agenda de 12 a 13  para un jueves
2. crear otra agenda de 13 a 14 para un martes y clonarla para el jueves del punto 1
3. la agenda clonada del punto 2 muestra conflicto con la agenda del punto 1

**Comment by Silvinagabriela** [comment]
Analizar User story Id 441

**Comment by milagrosn** [comment]
No se puede generar agendas para antes de la hora con el mismo profesional y misma prestación, por ejemplo:
1.- Existe agenda de niño sano de 10 a 12 hs. para profesional N
2.- Intento armar agenda igual pero para antes de la hora es decir: de 8 a 10 hs., sistema no permite generar la agenda por conflicto con profesional.
3.- Sistema si permite generar agenda cuando la armo con la hora fin, es decir de 12 a 13 hs por ejemplo.
