### ISSUE TITLE
PrestamosHC - Visualización de carpetas prestadas

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#815]
### Comportamiento actual
No se visualizan carpetas prestadas

### Resultado esperado 
Poder ver las carpetas que fueron prestadas y devolverlas. 
### Pasos para reproducir el problema 
1. prestar una carpeta
2. hacer clic en la solapa  "prestamos de carpetas"
3. No se visualiza la carpeta prestada en el punto 1

Testing 8082

**Comment by milagrosn** [comment]
Resuelto!
