### ISSUE TITLE
PrestamosHC/RUP - Nombre del archivo adjunto

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#817]
### Comportamiento actual
Cuando un paciente tiene varios documentos adjuntos no se puede identificar fácilmente cual es cual. 
### Resultado esperado 
Visualizar el nombre del documento adjunto para poder identificarlos
### Pasos para reproducir el problema 

![hc](https://user-images.githubusercontent.com/38788179/45694429-9e66d400-bb35-11e8-8563-f5f9af5f1edc.PNG)
![hc2](https://user-images.githubusercontent.com/38788179/45694430-9e66d400-bb35-11e8-8f86-ebc52a1d83f1.PNG)

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
