### ISSUE TITLE
PrestamosHC/RUP - Búsqueda por efector

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#818]
### Comportamiento actual
Para poder ver a que efector pertenece la HC adjunta se deben abrir una por una. 
### Resultado esperado 
Visualizar rápidamente a que efector pertenece la HC

### Pasos para reproducir el problema 
![hc3](https://user-images.githubusercontent.com/38788179/45694782-644a0200-bb36-11e8-9f74-828d6f7bc0e7.PNG)

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
