### ISSUE TITLE
Carga de paciente en agenda No Nominalizada

### ISSUE THREAD

**Issue by milagrosn** [andes/app#826]
### Comportamiento actual
* En la carga de pacientes para una agenda No nominalizada se puede cargar el mismo paciente  indefinidas veces .

### Resultado esperado 
* Que no se repita el mismo paciente

### Pasos para reproducir el problema 
1. Iniciar prestación en agenda no nominalizada
2. Cargar al mismo pacientes mas de una vez
3. Visualizar al paciente repetido.

**Comment by palita1991** [comment]
Resuelto en la v4.4.13
