### ISSUE TITLE
RUP: Agendas con conceptos predefinidos

### ISSUE THREAD

**Issue by milagrosn** [andes/app#827]
### Comportamiento actual
* Hay agendas como Screening de Otoemisión que al iniciarle la prestación ya trae conceptos predefinidos y para guardar la consulta aun cuando el paciente No Asistió, es necesario cargarle los campos. 
### Resultado esperado 
* que el sistema permita guardar este tipo de agendas sin cargarle datos, cuando el paciente no asistio por ejemplo
### Pasos para reproducir el problema 
1. iniciar prestacion se screening
2. cargar el concepto "No Asistio"
3. Intentar guardar

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
