### ISSUE TITLE
(DEMO) Nro. de HC repetidas 

### ISSUE THREAD

**Issue by milagrosn** [andes/app#831]
### Comportamiento actual
* El sistema permite generar un nro. de HC que ya existe. (solo una vez, la segunda vez que quiero generar el mismo nro. de HC se abre mensaje de error "Nro. de HC que ya existe")
### Resultado esperado 
* No permitir crear un nro. de HC que ya existe

### Pasos para reproducir el problema 
1. Desde punto de inicio al dar un turno, generarle al paciente un nro. de HC que ya existe
2. visualizar que toma el nro. ya existente en otro paciente.
3. 

![image](https://user-images.githubusercontent.com/39344609/45771349-40142100-bc1b-11e8-8293-30ec131a27ec.png)

**Comment by condorpiedra** [comment]
resuelto en versión https://github.com/andes/app/releases/tag/v3.8.0
