### ISSUE TITLE
MPI - Relación entre mas de 1 paciente

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#854]
### Comportamiento actual
* Al relacionar mas de un paciente por MPI. El primero se relaciona automaticamente pero el resto de las relaciones no. Ej. Si relaciono al paciente 1 con el paciente a, b y c, el paciente "a" toma la relación pero "b y c" no se refleja. 
### Resultado esperado 
* Que todas las relaciones ingresadas se visualicen en ambos registros. 

### Pasos para reproducir el problema 
1. partir de un paciente validado
2. hacer clic en relaciones
3. relacionar mas de un paciente
4.revisar el registro en el segundo paciente ingresado.

**Comment by NicoDino** [comment]
solucionado en mpi v4.5.0
