### ISSUE TITLE
Visualización de Turnos disponibles desde la app mobile

### ISSUE THREAD

**Issue by condorpiedra** [andes/app#863]
### Comportamiento actual
* El paciente ingresa a la app para solicitar un turno.  Selecciona un horario y antes de confirmar cancela para cambiar la hora.  Si en ese momento se asignaron turnos a diferentes pacientes en la vista de los turnos Disponibles, el paciente visualiza estos turnos aún como disponibles.  

### Resultado esperado 
* El usuario de la app mobile debería visualizar los datos actualizados en todo momento. Es decir se deberían volver a traer los datos de las agendas cada vez que se vuelve a la pantalla de 

### Pasos para reproducir el problema 
1. Loguearse en la app mobile- Ir a Mis turnos
2. Seleccionar un centro y presionar "Hay turnos disponibles" 
3. Elegir un horario y presionar "Solicitar"
4. Ir al gestor de agendas en la aplicación y realizar diferentes asignaciones d turnos
5. Presionar "Cancelar" en la app mobile
6. Ver la pantalla de Turnos Disponibles.  Se visualizan horarios ya asignados a otros pacientes

**Comment by sychus** [comment]
Solucionado! Igual este issue debería ir en la app mobile no? :-)

**Comment by condorpiedra** [comment]
:+1:    Si lo había puesto en este repositorio porque todas las operaciones fueron realizadas en el gestor y solamente use la app mobile para la visualización! pero lo muevo
