### ISSUE TITLE
APP MOBILE - Agendas con mas de una prestación

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#871]
### Comportamiento actual
Se quiere tomar turnos de odontología por la aplicación,  pero cuando la agenda tiene mas de una prestación (por ejemplo Consulta de niño sano y Consulta de odontología) no muestra la agenda en la aplicación. 

### Resultado esperado 
Visualizar todas las agendas que tengan turnos disponibles para la prestación requerida 
### Pasos para reproducir el problema 
1. crear una agenda con dos prestaciones 
2. publicarla
3. buscar dicha agenda desde la aplicación

**Comment by lucasgonzalezm** [comment]
Funciona bien ya esto
