### ISSUE TITLE
Modulo TOP - Solicitudes desde RUP

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#875]
### Comportamiento actual
Al cargar una solicitud desde RUP no se puede seleccionar el efector destino y queda registrada en el modulo top en ambas bandejas en el efector origen (salida y entrada)

### Resultado esperado 
Poder seleccionar la organización destino en RUP y visualizar la solicitud en dicho efector en bandeja de entrada. A su vez visualizar en el efector origen la solicitud en bandeja de salida. 

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by Silvinagabriela** [comment]
![top2](https://user-images.githubusercontent.com/38788179/46877579-925df180-ce17-11e8-9f35-7fc2e8d2d0b5.PNG)
![top1](https://user-images.githubusercontent.com/38788179/46877580-925df180-ce17-11e8-9659-5a01fef39f7a.PNG)

**Comment by milagrosn** [comment]
Resuelto!!!!
