### ISSUE TITLE
Rup - Odontograma: Error al validar la prestación

### ISSUE THREAD

**Issue by milagrosn** [andes/app#880]
### Comportamiento actual
* Cuando cargo piezas dentales en el odontograma con conceptos snomed . y quiero validar la prestación, se genera error en la consola y no me permite validar.

### Resultado esperado 
* Que me permita validar

### Pasos para reproducir el problema 
1. inicio prestación en consulta de odontología
2. cargo odontograma con algun concepto snomed
3. intentar validar

![image](https://user-images.githubusercontent.com/39344609/47025256-8173ef80-d139-11e8-97f9-507c111e2ce8.png)

**Comment by Silvinagabriela** [comment]
La prestación se valida, lo que sucede es que no se actualiza la pantalla.
