### ISSUE TITLE
RUP - Mapeo estático 

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#885]
### Comportamiento actual
Mapeos no disponibles
### Resultado esperado 
Mapeos: 
Debe mapear como: Control de salud de rutina del niño (Descripción CIE10)

Consulta de niño sano, al mes 
Consulta de niño sano, a los 2 meses
Consulta de niño sano, a los 21 meses
Consulta de niño sano, a los 2 años y medio
Consulta de niño sano, a los 3 años y medio

### Pasos para reproducir el problema 
1. 
2. 
3. 

![mapeo estatico](https://user-images.githubusercontent.com/39373693/47223961-ce9dce80-d390-11e8-9f80-bd12d0698bfe.PNG)

**Comment by condorpiedra** [comment]
Se resuleve agregando los conceptos al mapeo estático
