### ISSUE TITLE
CITAS - Agendas no nominalizadas. Huds del paciente

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#888]
### Comportamiento actual
MEJORA
No se visualiza en la HUDS del paciente, que éste haya participado en una actividad registrada en una agenda no nominalizada 
### Resultado esperado 
Que este tipo de registros forme parte de la HUDS del paciente. 

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by Silvinagabriela** [comment]
se cierra para US.
