### ISSUE TITLE
CITAS - agendas no nominalizadas 

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#890]
### Comportamiento actual
Al crear una agenda, si se selecciona la prestación actividades con la comunidad, el formato de la agenda se modifica para no ingresar cantidad de turnos. Pero si esta prestación se borra y se ingresa otra prestación (cualquiera), el formato de la agenda continua con las características de una no nominalizada.
### Resultado esperado 
Si se selecciona otra prestación que no sea no nominalizada el formato de la agenda debe mostrar cantidad y tipos de turnos. 
![no no](https://user-images.githubusercontent.com/39373693/47248393-7b536c80-d3e0-11e8-9c68-42e4cefdab5c.PNG)

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by milagrosn** [comment]
corregido!
