### ISSUE TITLE
RUP: Procedimientos de enfermería

### ISSUE THREAD

**Issue by milagrosn** [andes/app#909]
### Comportamiento actual
* En "procedimientos de enfermería" al cargar minuto superior a 60, se muestra mensaje de error 
### Resultado esperado 
* Que permita guardar y validar prestación con minutos superiores a los 60
### Pasos para reproducir el problema 
1. Iniciar prestación para consulta de enfermería
2. Cargar minutos superiores a 60
3. Ver mensaje de error

**Comment by sychus** [comment]
@milagrosn que es esto de procedimientos mayores a 60 minutos?. Hay que ver en que requerimiento estaba esto. Porque sino van a poner cualquier cosa en la resolución del issue. ¿Cuantos minutos como máximo se requiere? ¿tiene sentido que tenga un tiempo máximo? Porque eventualmente habría que sacar la restricción.
