### ISSUE TITLE
Préstamos de carpetas: Préstamos manuales de carpetas

### ISSUE THREAD

**Issue by condorpiedra** [andes/app#915]
### Comportamiento actual
* Se busca un paciente que posee número de carpeta en un efector pero no se le ha asignado turnos desde CITAS.  Muestra un mensaje que no se puede realizar el préstamo.

### Resultado esperado 
* Poder realizar préstamos manuales independientemente si el paciente tiene un turno asignado.

### Pasos para reproducir el problema 
1. Ingresar al módulo de préstamos de carpetas.
2. Presionar en el botón "Agregar solicitud manual".
3. Se busca un paciente que no tenga turno pero tenga carpeta en el efector.
4. Aparece un mensaje que el paciente no posee una carpeta en esta Institución.

**Comment by milagrosn** [comment]
Resuelto!
