### ISSUE TITLE
RUP - Prestación: Actividades con la comunidad

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#918]
### Comportamiento actual
No se visualiza el DNI del paciente al momento de agregarlo en el informe de la prestación.

### Resultado esperado 
Mejoras:
-Visualizar el DNI del paciente en el resumen de la actividad.

### Pasos para reproducir el problema 
1. Iniciar la prestación actividades con la comunidad
2. ingresar pacientes desde el buscador presente en el componente del informe.
3. seleccionar paciente.

**Comment by Silvinagabriela** [comment]
se cierra para sumar a la US de prestaciones no nominalizadas.
