### ISSUE TITLE
RUP: Consulta Niño Sano

### ISSUE THREAD

**Issue by milagrosn** [andes/app#920]
### Comportamiento actual
* Cuando inicio prestación de Niño Sano, en los sugeridos, se visualiza el procedimiento de "Consulta de niño sano a los 21 meses " repetido

### Resultado esperado 
* Que el concepto "Consulta de niño sano a los 21 meses se visualice una vez"

### Pasos para reproducir el problema 
1. iniciar prestación a paciente de consulta de niño sano
2. ver en sugeridos el concepto niño sano a los 21 meses
3. visualizar q se ve repetido

![image](https://user-images.githubusercontent.com/39344609/48073630-ead9a200-e1bd-11e8-9530-d37b7404975a.png)

**Comment by condorpiedra** [comment]
Se quita de los conceptos sugeridos Consulta de Niño Sano, A los 21 Meses (Procedimiento)
