### ISSUE TITLE
Puco, mensaje de error al enviar mensaje

### ISSUE THREAD

**Issue by milagrosn** [andes/app#921]
### Comportamiento actual
* Desde Puco al querer enviar una sugerencia desde el botón, se abre ventana de error

### Resultado esperado 
* Poder enviar mensaje de sugerencia

### Pasos para reproducir el problema 
1. Ingresar a Puco
2. enviar mensaje de sugerencia desde el botón
3. ver ventana de error

![image](https://user-images.githubusercontent.com/39344609/48079241-bcfa5a80-e1c9-11e8-9a52-aa7283487e59.png)

**Comment by sychus** [comment]
Estimados: El problema se debe a que el componente está en una ruta con autenticación. Cuando el acceso desde PUCO es sin loguearse da error 401! 
Posibilidades para analizar:
1) Al momento de hacer una sugerencia que solicite login.
2) Ocultar el botón de sugerencias cuando se está en modo público y habilitarlo cuando está en logueado.
3) Dejar público el componente de sugerencias (NO LO RECOMIENDO ya que se podría explotar el mail sender) en caso de querer tener esta posibilidad pública hay que implementar el reject para bots.

**Comment by condorpiedra** [comment]
@sychus muy buenas sugerencias! Gracias!

**Comment by milagrosn** [comment]
Cuando estoy logueada sigue mostrado el mismo error.
![image](https://user-images.githubusercontent.com/39344609/48955046-c6eebe00-ef2a-11e8-97f6-19e3d15743ab.png)
