### ISSUE TITLE
Gestor de usuarios - agregar efector

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#925]
### Comportamiento actual
Al momento de agregar un efector, no distingue si este permiso existe o no permitiendo agregar nuevamente el efector y eliminando los permisos que ya tenía. 

### Resultado esperado 
No permitir agregar un efector ya existente en los permisos del usuario.
### Pasos para reproducir el problema 
1. buscar un usuario
2. agregar un efector y habilitar permisos
3. guardar
4.volver a agregar el mismo efector.

**Comment by Silvinagabriela** [comment]
idem issus #916
