### ISSUE TITLE
CITAS: Agendas pendientes de auditoría

### ISSUE THREAD

**Issue by Silvinagarcia** [andes/app#928]
### Comportamiento actual
Muestra en pendiente de auditoria agendas que no tienen pacientes.

### Resultado esperado 
-Mostrar en pendiente de auditoría solo aquellas agendas que tengan turnos dados.
-Aquellas agendas que hayan quedado sin turnos pasarlas directamente a auditadas o identificarlas de alguna otra manera. 

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by milagrosn** [comment]
Resuelto, ahora las agendas quedan Auditadas!
