### ISSUE TITLE
Definición incorrecta de la interface para campos booleanos

### ISSUE THREAD

**Issue by kroce** [andes/app#946]
### Comportamiento actual
* En la interfaz IPrestacionGetParams habría que manejar los boolean con el tipo nativo, y no parsearlo como "Si" o "No"

**Comment by liquid36** [comment]
@silviroa Habían hecho algunos cambios sobre esto, no?

**Comment by lucasgonzalezm** [comment]
Han hecho una nueva interfaz, sin los e
