### ISSUE TITLE
CITAS - Agendas Dinámicas con una prestación

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#948]
### Comportamiento actual
Al ingresar un paciente en una agenda dinámica de una prestación el botón guardar no responde y muestra en consola el siguiente error:  

### Resultado esperado 
Poder ingresar  pacientes en una agenda dinámica desde RUP

### Pasos para reproducir el problema 
1. crear una agenda dinámica con una prestación
2. publicarla
3. ingresar pacientes desde RUP

![image](https://user-images.githubusercontent.com/38788179/48418982-89718000-e735-11e8-8561-3c3121d50952.png)

**Comment by Silvinagabriela** [comment]
Desde punto de inicio CITAS funciona correctamente.

**Comment by condorpiedra** [comment]
resuelto en v4.0.2
