### ISSUE TITLE
Prestamos de Carpetas: Imprimir Solicitudes

### ISSUE THREAD

**Issue by milagrosn** [andes/app#952]
### Comportamiento actual
* Cuando quiero imprimir el listado de las solicitudes, se imprimen las pestañas (solicitudes, prestamos, historial) para la impresión.

### Resultado esperado 
* Que esté visible el titulo y el listado de los prestamos; y no las pestañas

### Pasos para reproducir el problema 
1. Ingresar al modulo Prestamos de carpeta, 
2. Imprimir listado
3. Visualizar las pestañas del modulo

![Uploading image.png…]()

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
