### ISSUE TITLE
MPI: similitud con paciente candidato

### ISSUE THREAD

**Issue by milagrosn** [andes/app#955]
### Comportamiento actual
* En MPI se busca un paciente (DNI y sexo), si el paciente ya está validado me muestra los pacientes candidatos (similitudes). Cuando elijo uno de los candidatos y quiero guardar me muestra mensaje de error (adjunto captura)

### Resultado esperado 
* Que me permita elegir el paciente seleccionado (de los candidatos posibles)
Pasos:
1. Buscar paciente ingresando dni y sexo (y que tenga candidatos similares)
2. Elegir el candidato que corresponda
3. Se abre ventana de error

![image](https://user-images.githubusercontent.com/39344609/48501601-52c26500-e81c-11e8-8b78-ee2ca6313c02.png)

**Comment by NicoDino** [comment]
:fire_engine:

**Comment by milagrosn** [comment]
Resuelto
