### ISSUE TITLE
TOP: Acumulación de Reglas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#962]
### Comportamiento actual
* Cuando creo reglas para un efector, y luego creo reglas a otro efector,en el momento de crear una solicitud se pueden ver que  la "Prestación destino" se van acumulando, no discrimina que regla es para cada efector.

### Resultado esperado 
* Que las reglas que genero para un efector sean exclusivos del mismo y no se acumulen con las que se  generaron en otro efector.

### Pasos para reproducir el problema 
1. Generar regla para un efector
2. Generar regla para otro efector
3. Visualizar en la "prestación destino" (cuando genero una nueva solicitud) de los efectores que ambas reglas se acumulan, es decir que están disponibles las reglas creadas para los 2 efectores.

**Comment by milagrosn** [comment]
Esto ocurre en servidor de Demo

**Comment by kroce** [comment]
@milagrosn podés verificar si esto sigue pasando? Así cerramos este issue

**Comment by milagrosn** [comment]
@kroce sigue pasando!

**Comment by milagrosn** [comment]
Resuelto!!!
