### ISSUE TITLE
Botones - estilos

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#966]
### Vista actual
Se adjuntan imágenes. 
1- Modulo TOP: Reglas - Botón "cancelar" -> cambiar por "volver" Se sugiere cambiar el color a celeste ya que el rojo esta presente en funciones como cancelar, borrar, suspender. 
2-Modulo TOP: Reglas pop up información -> cambiar a color naranja ya que es el color presente en alertas de información.
3-Modulo TOP: Reglas global: Botón Volver se sugiere cambiar el color a celeste ya que el rojo esta presente en funciones como cancelar, borrar, suspender. 
4- - RUP - Ver HUDS de un paciente  -> Botón "cancelar" cambiar por "punto de inicio" ya que el comportamiento del botón no implica cancelar ninguna operación sino volver al punto de inicio del profesional.

![image](https://user-images.githubusercontent.com/38788179/48903385-2b7e2000-ee3a-11e8-98c6-4a7a6fca07a8.png)
![image](https://user-images.githubusercontent.com/38788179/48903397-3638b500-ee3a-11e8-8fa9-653b19ed7f27.png)
![image](https://user-images.githubusercontent.com/38788179/48903406-405ab380-ee3a-11e8-8bfe-0b3c56cf0630.png)
![image](https://user-images.githubusercontent.com/38788179/48903496-739d4280-ee3a-11e8-97a4-1a13c170a4f7.png)
![image](https://user-images.githubusercontent.com/38788179/48903951-adbb1400-ee3b-11e8-877e-4e0c4e3ce86e.png)

### Resultado esperado 
* ¿Que espera que suceda?

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by palita1991** [comment]
Se cierra para cargar en US en Open Project.
