### ISSUE TITLE
TOP: turnos en agendas dinamicas

### ISSUE THREAD

**Issue by milagrosn** [andes/app#968]
### Comportamiento actual
* Cuando quiero dar un turno de una solicitud pendiente, me muestra disponible agenda dinámica (que no tiene turnos con llave) y se genera con éxito el turno, pero desde las solicitudes muestra al paciente "Pendiente" como si no se hubiera generado el turno.

### Resultado esperado 
* Que no muestre agendas dinámicas (ya que no tienen turnos con llave), o en todo caso que si se genera el turno muestre la solicitud con el "turno dado".

### Pasos para reproducir el problema 
1. Desde una solicitud pendiente intentar dar turno
2. Visualizar que en el calendario se muestran también agendas dinámicas, dar turno para este tipo de agendas
3. Ver en la solicitud que el paciente sigue con el turno pendiente.

![image](https://user-images.githubusercontent.com/39344609/48907004-08a53900-ee45-11e8-8d8c-877acdfb1bf9.png)

![image](https://user-images.githubusercontent.com/39344609/48906966-edd2c480-ee44-11e8-9d87-053f4b2a9d65.png)

**Comment by Silvinagabriela** [comment]
Resuelto
