### ISSUE TITLE
RUP: Impresión de Informe - Screening

### ISSUE THREAD

**Issue by milagrosn** [andes/app#969]
### Comportamiento actual
* Para la prestación "Screening de otoemision acustica neonatal" la descarga del informe pdf no muestra información
 
### Resultado esperado 
* poder visualizar la carga del profesional en el informe

### Pasos para reproducir el problema 
1. iniciar prestación para la prestación de screening neonatal
2. cargar información en cada uno de los conceptos que aparecen
3. Visualizar la impresión del  informe PDF

![image](https://user-images.githubusercontent.com/39344609/48914357-f8e41f80-ee59-11e8-8b0d-ca889b2028ba.png)

**Comment by fersastre** [comment]
Fixeado PR #520 en la api
