### ISSUE TITLE
Colonoscopía - Agregar producto como contenido

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/app#972]
### Comportamiento actual
Al agregar un producto como contenido en otro componente, se solapan los campos.

### Resultado esperado 
Que el concepto agregado se amolde y se visualice correctamente. 

![image](https://user-images.githubusercontent.com/38788179/48939492-2af59000-eef3-11e8-97f8-c851dfc077bf.png)

### Pasos para reproducir el problema 
1. 
2. 
3.

**Comment by milagrosn** [comment]
Resuelto!
