### ISSUE TITLE
Solicitud en agenda suspendida

### ISSUE THREAD

**Issue by milagrosn** [andes/app#982]
### Comportamiento actual
* Cuando se suspende una agenda con turnos dados desde modulo TOP, no se ve reflejado en el mismo; es decir sigue visualizándose en el modulo como un  turno pendiente.

### Resultado esperado 
* Que se muestre una leyenda o mensaje que ese turno/agenda fue suspendida

### Pasos para reproducir el problema 
1. Dar un turno desde modulo top
2. Buscar agenda del turno dado y suspender agenda
3. Visualizar desde el modulo que sigue figurando dicha solicitud como "Turno Dado"

**Comment by NicoDino** [comment]
Este comportamiento no estaba contemplado dentro de los requerimientos, entra en las propuestas de mejoras.
