### ISSUE TITLE
RUP: Sobreturnos - Registrar inasistencia

### ISSUE THREAD

**Issue by milagrosn** [andes/app#995]
### Comportamiento actual
* En los sobreturnos dados, cuando registro inasistencia a un paciente, me queda habilitado el botón "Iniciar Prestación" pudiendo iniciar el mismo. También ocurre que no aparece el botón para revertir la inasistencia

### Resultado esperado 
* No mostrar el botón de iniciar prestación cuando registro inasistencia a un paciente, y que bajo el mensaje "no asistió" (que se ve todo junto "NOASISTIO") que me quede habilitado el botón de Revertir asistencia como en los turnos.
### Pasos para reproducir el problema 
1. Desde un paciente con sobreturno, registrarle la inasistencia.
2. Visualizar que se puede iniciar prestación
3. Visualizar que el botón revertir inasistencia no se visualiza

![image](https://user-images.githubusercontent.com/39344609/49449737-4ea1bb80-f7ba-11e8-954c-603fdf2105fb.png)

**Comment by NahirSaddiRTO** [comment]
@milagrosn Solución en pull request #1035
