### ISSUE TITLE
RUP: Registrar inasistencia

### ISSUE THREAD

**Issue by milagrosn** [andes/app#999]
### Comportamiento actual
* Para la prestación "screening de otoemisión acústica neonatal (procedimiento)", cuando inicio prestación y después quiero darle "NOASISTIO" desde punto de inicio:Consultorio, no es posible. Se puede cargar como concepto snomed "no asistio" pero se debe completar los conceptos precargados de la prestación. 

### Resultado esperado 
* Cuando inicio prestación por error (para cualquier prestación en especial para Screening) y vuelvo a la agenda que no se inhabilite el botón "NOASISTIO".

### Pasos para reproducir el problema 
1. Iniciar prestación a paciente para Screening 
2. Volver  apunto de inicio, visualizar que al paciente se le inhabilita el botón "NOASISTIO"
3. 

![image](https://user-images.githubusercontent.com/39344609/49535273-8a17b500-f8a2-11e8-8954-09b7b5ddbaaa.png)

**Comment by NahirSaddiRTO** [comment]
@milagrosn solucionado en el pull request RUP: Sobreturnos - Registrar inasistencia #1035
